---
format:
    html:
        table-of-contents: false
        css: event-page-styles.css
page-layout: full
pagetitle: 'The Carpentries (software, data, library) instructor training – call for application'

# Event categories
event:
  title: 'The Carpentries (software, data, library) instructor training – call for application'
  description: ""
  categories:  'Application call'
  date: "November 13, 2023"
  end_date: "November 13, 2023"
  time: "8:00"
  location:
    name: "Online (Zoom)"
    address: ""
    map_url: ""
  format:
    type: 'Application call'
    detail: ""
  language:
    primary: "English"
    primary-code: "en"
    detail: "NA"
links:
  registration: ""
  materials: ""
  workshop_website: ""

event_description:
  - ""

instructors:
  - name: ""
    url: ""

helpers:
  - name: ""

contact:
  name: ""
  email: ""
---
<!-- MANDAORY SECTION START  -->
<link rel = "stylesheet"  href = "https://cdn.jsdelivr.net/npm/bootstrap-icons@5.6.2/font/bootstrap-icons.css">

<h1 class="fs-1 text-primary"> {{< meta event.title >}} </h1>

{{< include templates/_setup.qmd >}}
{{< include templates/_info_boxes.qmd >}}
{{< include templates/_register_button.qmd >}}
<!-- MANDAORY SECTION END  -->



<!-- DETAILED EVENT DESCRIPTION HERE OR USE THE TEMPLATE BELOW TO INCLUDE THE STANDARD DESCRIPTION SECTION -->
<!-- {{< include templates/_event_description.qmd >}} -->

<p>Are you interested in <strong>becoming a certified instructor to teach your computing, software, and data skills that facilitate open and reproducible research?</strong></p><p>Through generous funding from the Munich Center for Machine Learning (<a href="https://mcml.ai" target="_blank">MCML</a>), the LMU Open Science Center (<a href="https://www.osc.uni-muenchen.de/index.html" target="_blank">OSC</a>) and MCML have established an institutional membership between LMU Munich and <a href="https://carpentries.org/" target="_blank">The Carpentries</a>. The Carpentries is a non-profit, community-led organisation, which specialises in teaching basic <a href="https://software-carpentry.org/" target="_blank">Software</a>, <a href="https://datacarpentry.org/" target="_blank">Data</a>, or <a href="https://librarycarpentry.org/" target="_blank">Library</a> skills to researchers of all career stages and across disciplines, in an inclusive environment. By training trainers to teach reproducible tools that increase integrity, credibility, and reuse, this partnership will foster the expansion of the open science community in Munich.</p><p>As part of the institutional membership, <strong>we are able to offer training, free of charge, for 15 members (students or staff) of the LMU and TUM Universities to qualify as <a href="https://carpentries.org/teach/" target="_blank">instructors for The Carpentries</a></strong>. Five of these seats are reserved in priority for MCML members. The training involves attendance of a 16-hour online <a href="https://carpentries.github.io/instructor-training/" target="_blank">event</a>, followed by a simple check-out process. Applicants are expected to already know or be willing to learn on their own at least one of the practical skills they would teach in their future workshops (e.g. R and/or Python and/or Unix Shell and/or Git, and/or Open Refine and/or SQL, etc.), as the instructor training will focus on the didactics around teaching said skill(s). Certified instructors will then be able to help deliver <a href="https://software-carpentry.org/" target="_blank">Software</a>, <a href="https://datacarpentry.org/" target="_blank">Data</a>, or <a href="https://librarycarpentry.org/" target="_blank">Library</a> Carpentry workshops using the existing open source training material from the Carpentries, for example by co-teaching a workshop for their research group, department, or in a Faculty where computing skills training isn’t currently part of official curricula. <strong>We expect newly trained instructors to be involved in the delivery of at least one workshop in LMU or TU Munich within 12 months of completing the training.</strong></p><p>If interested, please read the information below and fill out this <a href="https://tellmi.psy.lmu.de/formr/carpentries-application" target="_blank">application form</a>. If you have any questions, feel free to get in touch with the OSC coordinator, Dr. Malika Ihle (<a class="g-link-mail" href="mailto:malika.ihle@lmu.de" title="Send email to: malika.ihle@lmu.de">malika.ihle@lmu.de</a>), or the MCML open science transfer coordinator, Dr. Moritz Herrmann (<a class="g-link-mail" href="mailto:moritz.herrmann@stat.uni-muenchen.de" title="Send email to: moritz.herrmann@stat.uni-muenchen.de">moritz.herrmann@stat.uni-muenchen.de</a>).</p><h2>Timeline</h2><p><strong>Application deadline:</strong> 13 November 2023, 08:00 CET</p><p><strong>Instructor training:</strong> Those offered a place are encouraged to attend the online training as soon as possible, from November 2023. Participation for the whole duration of the training is required. This 16-hour event can take place over 2 or 4 days. Minimally two sessions are provided each month, and new dates are shared every quarter. Please see the <a href="https://carpentries.github.io/instructor-training/training_calendar.html" target="_blank">training calendar</a> for upcoming sessions.</p><p><strong>Workshop delivery:</strong> We expect newly trained instructors to be involved in the delivery of at least one Carpentries workshop at the LMU or TU Munich within one year of completing the training.</p><h2>Eligibility criteria</h2><p><br>This call is aimed at postgraduate research students, research staff or fellows, and research support staff from any department, who expect to be based in Munich at least through the end of June 2025.</p><h2>Selection criteria</h2><p><br>Places will be allocated in line with the goal of building a sustainable community of instructors based in Munich. Criteria include:</p><ul>
<li>career stage, motivation, and experience (i.e., balance between early-career researchers interested in building a community of peers, and permanent university staff already involved in training);</li>
<li>representation across Faculties (i.e., balance between disciplines with high demand for training in computing skills, and disciplines with limited training opportunities in this area);</li>
<li>previous involvement with the LMU Open Science Center and/or with The Carpentries (both favoured, but not necessary);</li>
<li>a commitment to diversity, equity, inclusion, and accessibility, to ensure that all future workshop participants are able to access training in a welcoming environment.</li>
</ul>
<p><br>We warmly encourage recent practitioners of software, data or library skills (e.g. students or early career researchers), and members who identify with groups that have been historically excluded from computer science and related fields (e.g., women, people of colour and/or from ethnic minority backgrounds, people with disabilities, and members of the LGBTQIA+ community) to apply.</p><p>Are you already a certified Carpentries instructor and want to contribute to the teaching of future workshops? Email <a class="g-link-mail" href="mailto:malika.ihle@lmu.de" title="Send email to: malika.ihle@lmu.de">malika.ihle@lmu.de</a> to be added to our local instructors mailing list!</p><div class="g-clear"></div>



<!-- MANDAORY SECTION START  -->
<!-- _event_description.qmd template should always be at bottom -->
{{< include templates/_instructors_helpers_contact.qmd >}}
<!-- MANDAORY SECTION END  -->
