---
title: 'Workshop: Navigating the Landscape of Scientific Integrity: Insights into
  Open Science, Replicability, data sharing and questionable research practices in
  the field of medicine'
categories: Symposium
date: '2024-11-27'
event:
  description: ''
  date: '2024-11-27'
  end_date: ''
  time: ''
  location:
    name: CAS LMU, Seestraße 13, 80802 Munich
    address: ''
    map_url: ''
  format:
    type: Symposium
    detail: ''
  language:
    primary: English
    primary-code: en
    detail: ''
links:
  registration: ''
  materials: ''
  workshop_website: ''
event_description: ''
instructors:
  - name: ''
    url: ''
helpers:
  - name: ''
contact:
  name: Anne-Laure Boulesteix
  email: boulesteix@ibe.med.uni-muenchen.de
organizers:
  - name: Prof. Dr. Anne-Laure Boulesteix
    url: ''
  - name: Dr. Sabine Hoffmann
    url: ''
host:
  - name: LMU Center for Advanced Studies (CAS)
    url: ''
presenters:
  - name: Tim Morris
    url: ''
  - name: Laure Wynants
    url: ''
  - name: Balazs Aczel
    url: ''
  - name: Leonhard Held
    url: ''
  - name: Willi Sauerbrei
    url: ''
  - name: Sarah Friedrich
    url: ''
  - name: Ulrich Mansmann
    url: ''

---
<!-- MANDAORY SECTION START  -->

{{< include templates/_setup.qmd >}}
{{< include templates/_info_boxes.qmd >}}
{{< include templates/_register_button.qmd >}}
<!-- MANDAORY SECTION END  -->

<br>

<!-- DETAILED EVENT DESCRIPTION HERE OR USE THE TEMPLATE BELOW TO INCLUDE THE STANDARD DESCRIPTION SECTION -->
<!-- {{< include templates/_event_description.qmd >}} -->

<p> </p><p><strong>Keynote lectures</strong> by:</p><ul>
<li>Tim Morris (UCL, UK, tentative keywords: estimands, good statistical practice in trials)</li>
<li>Laure Wynants (Leuven, BE, tentative keywords : good practice in prognostic modelling, meta-research)</li>
<li>Balazs Aczel (Budapest, HU, tentative keywords : meta-research, multi-analyst studies)</li>
<li>Leonhard Held (Zürich, CH, replicability, data sharing)</li>
<li>Willi Sauerbrei (Freiburg, tentative keywords: structured reporting, STRATOS)</li>
<li>Sarah Friedrich (Augsburg, tentative keywords: synthetic data/anonymization)</li>
<li>Ulrich Mansmann (LMU, tentative keywords: data sharing)</li>
</ul>
<p>The program is not yet finalized and you are welcome to make <strong>suggestions</strong> by e-mail to <a class="g-link-mail" href="mailto:boulesteix@ibe.med.uni-muenchen.de" title="Send email to: boulesteix@ibe.med.uni-muenchen.de">boulesteix@ibe.med.uni-muenchen.de</a> and <a class="g-link-mail" href="mailto:sabine.hoffmann@stat.uni-muenchen.de" title="Send email to: sabine.hoffmann@stat.uni-muenchen.de">sabine.hoffmann@stat.uni-muenchen.de</a>.</p><p>The workshop is part of the <strong>CAS Research Focus „Medical Data Processing" </strong>(<a href="https://www.cas.lmu.de/en/programs/cas-research-focuses/medical-data-processing/" target="_blank">https://www.cas.lmu.de/en/programs/cas-research-focuses/medical-data-processing/</a>).</p><p>You can already <strong>register</strong> at <a href="mailto:info@cas.lmu.de" target="_blank">info@cas.lmu.de</a>.</p><div class="g-clear"></div>



<!-- MANDAORY SECTION START  -->
<!-- _event_description.qmd template should always be at bottom -->
{{< include templates/_instructors_helpers_contact.qmd >}}
<!-- MANDAORY SECTION END  -->
