---
title: The Replication Crisis' Positive Impact on Research
categories: ReproducibiliTea Journal Club
event:
  description: ''
  start_date: '2024-01-12'
  end_date: ''
  time: ''
  location:
    name: LMU Open Science Center (Giselastr.)
    address: Leopoldstraße 13, Room 3322, 80802 Munich
    map_url: https://www.google.com/maps/place/Ludwig-Maximilian-Universit%C3%A4t+M%C3%BCnchen/@48.1559372,11.5833416,19.19z/data=!3m1!5s0x479e75bf863d5581:0x29d36540810c2590!4m6!3m5!1s0x479e75c07933e683:0x4851cac28ba68cb4!8m2!3d48.1558072!4d11.5829777!16s%2Fg%2F1hc2d61v7?entry=ttu&g_ep=EgoyMDI2MDUyMC4wIKXMDSoASAFQAw%3D%3D
  format:
    type: Hybrid
    detail: ''
  language:
    primary: English
    primary-code: en
    detail: ''
links:
  registration: ''
  materials: https://doi.org/10.1038/s44271-023-00003-2
  workshop_website: ''
event_description: ''
instructors:
- name: ''
  url: ''
helpers:
- name: ''
contact:
  name: ReproducibiliTea
  email: reproducibilitea.munich@gmail.com
organizers:
- name: Laura Goetz
  url: ''
- name: Viktoria Wiegelmann
  url: ''
- name: Gracia Prüm
  url: ''
- name: Finia Loeb
  url: ''
- name: Alp Kaan Aksu
  url: ''
- name: Julian Lange
  url: ''
host:
- name: ReproducibiliTea Team
  url: ''
presenters:
- name: Gracia Prüm
  url: ''
template: templates/event-template.html
filters:
    - templates/process-event-yaml.lua
---

<br>

 

<p>We invite you to attend to the sixth session of our journal club this semester. In this session, we will discuss how the replication crisis has actually led to improvements in how research is conducted, leading to what's now known as the 'credibility revolution'. Discussing the paper "The replication crisis has led to positive structural, procedural, and community changes" by Korbmacher et al., we will examine the benefits that have emerged from this time period for research practices and the scientific community.</p><p><strong>Procedure: </strong>One member of the organizing team, Gracia Prüm, will summarise the paper by Korbmacher et al. There will then be an open discussion where you can contribute your own thoughts and questions. Finally, there will be time to get to know each other and talk in smaller groups.</p><p><strong>About the journal club: </strong><a href="/partners/local-os-initiatives/reproducibilitea.qmd" title="ReproducibiliTea Journal Club">Here</a> you can find further information about the concept of the journal club.</p><p>You are cordially invited to attend our upcoming meetings! To stay updated and receive notifications about these gatherings and the selected papers, you can either subscribe to our mailing list by clicking on this link: <a href="https://lists.lrz.de/mailman/listinfo/reproducibilitea">https://lists.lrz.de/mailman/listinfo/reproducibilitea</a>, or you can send an email to <a class="g-link-mail" href="mailto:reproducibilitea.munich@gmail.com" title="Send email to: reproducibilitea.munich@gmail.com">reproducibilitea.munich@gmail.com</a>. There is no requirement to have read the designated paper before each session, although it could be beneficial.</p><p>The organization team is looking forward to seeing you at one of the next journal club sessions.</p><p>organization team:</p><ul style="list-style-type: square;">
<li>Laura Goetz, Graduate student in Medicine and Psychology</li>
<li>Viktoria Wiegelmann, Undergraduate student in Psychology</li>
<li>Gracia Prüm, Undergraduate student in Psychology</li>
<li>Finia Loeb, Undergraduate student in Psychology</li>
<li>Alp Kaan Aksu, Undergraduate student in Psychology and Computer Science</li>
<li>Julian Lange, PhD student in Statistics</li>
</ul>
<p> </p><div class="g-clear"></div>



 
