---
title: Creating Interactive Graphics in R with Plotly
categories: Workshop
event:
  card_description: ''
  start_date: '2024-07-11'
  end_date: ''
  time: ''
  description: ''
  location:
    name: LMU Open Science Center (Giselastr.)
    address: Leopoldstraße 13, Room 3322, 80802 Munich
    map_url: https://www.google.com/maps/place/Ludwig-Maximilian-Universit%C3%A4t+M%C3%BCnchen/@48.1559372,11.5833416,19.19z/data=!3m1!5s0x479e75bf863d5581:0x29d36540810c2590!4m6!3m5!1s0x479e75c07933e683:0x4851cac28ba68cb4!8m2!3d48.1558072!4d11.5829777!16s%2Fg%2F1hc2d61v7?entry=ttu&g_ep=EgoyMDI2MDUyMC4wIKXMDSoASAFQAw%3D%3D
    type: In-Person
    detail: ''
  language:
    primary: English
    primary-code: en
    detail: ''
links:
  registration: ''
  materials: ''
  workshop_website: ''
instructors:
  - name: Maximilian Frank
    url: ''
helpers:
  - name: ''
contact:
  name: Malika Ihle
  email: malika.ihle@lmu.de
organizers:
  - name: Dr. Angelika Stefan
    url: ''
  - name: Lena Schiestel
    url: ''
host:
  - name: Open Science Initiative for Psychology (OSIP)
    url: ''

template: templates/event-template.html
filters:
    - templates/process-event-yaml.lua
---

<br>

 

<p>In this workshop, we will explore how the Plotly package in R can transform traditional research outputs into dynamic, interactive graphics that foster greater engagement and understanding. By integrating Plotly's capabilities into your research dissemination practices, you can enhance the accessibility and impact of your findings.</p><p><strong>Target audience:</strong> This session is designed for researchers across all disciplines who are interested in learning new advanced visualization techniques. If you've ever been frustrated that a graphic couldn't communicate what you wanted it to, this workshop is for you. The workshop will be conducted in R, other programming languages are welcomed as Plotly can also be used in a Python environment but not covered by the workshop itself.</p><p><strong>Prerequisites:</strong> Basic R programming skills</p>



 
