---
title: Code Documentation
categories: Hacky Hour
date: '2024-05-27'
event:
  title: Code Documentation
  description: ''
  date: '2024-05-27'
  end_date: ''
  time: ''
  location:
    name: Wikipedia Munich, Angertorstraße 3
    address: ''
    map_url: ''
  format:
    type: Hacky Hour
    detail: ''
  language:
    primary: English
    primary-code: en
    detail: ''
links:
  registration: ''
  materials: ''
  workshop_website: ''
event_description: ''
instructors:
  - name: ''
    url: ''
helpers:
  - name: ''
contact:
  name: Malika Ihle
  email: malika.ihle@lmu.de
organizers:
  - name: Dr. Malika Ihle
    url: ''
host:
  - name: LMU Open Science Center
    url: ''

---
<!-- MANDAORY SECTION START  -->

{{< include templates/_setup.qmd >}}
{{< include templates/_info_boxes.qmd >}}
{{< include templates/_register_button.qmd >}}
<!-- MANDAORY SECTION END  -->

<br>

<!-- DETAILED EVENT DESCRIPTION HERE OR USE THE TEMPLATE BELOW TO INCLUDE THE STANDARD DESCRIPTION SECTION -->
<!-- {{< include templates/_event_description.qmd >}} -->

<p>In this session, we will discuss the differences between code commenting and documenting and exchange tips on best practices!</p><p><strong>Possible resources to prepare your session’s hack:</strong></p><ul>
<li>
<a href="https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-readmes">How to write good READMEs for your code repositories</a> to tell others why your project is useful and what they can do with it</li>
<li>
<a href="https://docs.github.com/en/communities/documenting-your-project-with-wikis/about-wikis">How to write good WIKIs for your projects</a> so that others can use and contribute to your project.</li>
<li><a href="https://realpython.com/documenting-python-code/" target="_blank">Python Documentation techniques</a></li>
</ul>
<div></div><p><strong>Sessions’ agenda:</strong></p><ul>
<li>Brief round of introductions and description of the problems you’ll be working on during that session</li>
<li>Formation of possible groups or tandems, if participants have tips to exchange on certain topics</li>
<li>Hack</li>
<li>Wrap-up: progress and next steps</li>
</ul>
<p>Learn more about the Hacky Hour initiative <a href="../../meetups/hackyhour/index.html" title="Hacky Hour">here</a>.</p><div class="g-clear"></div>



<!-- MANDAORY SECTION START  -->
<!-- _event_description.qmd template should always be at bottom -->
{{< include templates/_instructors_helpers_contact.qmd >}}
<!-- MANDAORY SECTION END  -->
