---
title: Reproducible Manuscripts with Quarto
categories: Workshop
event:
  description: ''
  start_date: '2024-03-06'
  end_date: ''
  time: ''
  location:
    name: LMU Open Science Center (Giselastr.) Hybrid (Leopoldstraße 13, room 3322, Munich and via Zoom)
    address: Leopoldstraße 13, Room 3322, 80802 Munich
    map_url: https://www.google.com/maps/place/Ludwig-Maximilian-Universit%C3%A4t+M%C3%BCnchen/@48.1559372,11.5833416,19.19z/data=!3m1!5s0x479e75bf863d5581:0x29d36540810c2590!4m6!3m5!1s0x479e75c07933e683:0x4851cac28ba68cb4!8m2!3d48.1558072!4d11.5829777!16s%2Fg%2F1hc2d61v7?entry=ttu&g_ep=EgoyMDI2MDUyMC4wIKXMDSoASAFQAw%3D%3D
  format:
    type: Hybrid
    detail: ''
  language:
    primary: English
    primary-code: en
    detail: ''
links:
  registration: ''
  materials: https://lmu-osc.github.io/introduction-to-Quarto/
  workshop_website: ''
event_description: ''
instructors:
- name: Dr. Florian Pargent
  url: ''
- name: Florian Kohrt
  url: ''
helpers:
- name: ''
contact:
  name: Malika Ihle
  email: malika.ihle@lmu.de
organizers:
- name: Dr. Malika Ihle
  url: ''
host:
- name: LMU Open Science Center
  url: ''
template: templates/event-template.html
filters:
    - templates/process-event-yaml.lua
---

<br>

 

<p>Quarto makes transparent and reproducible data analysis simple and fun. In a nutshell, Quarto lets you mix text written in markdown with chunks of executable code written in, e.g., R or Python. You can use it for interactive notebooks, and export to a large number of formats including HTML, PDF/LaTeX, Microsoft Word or PowerPoint, or even interactive websites. In this workshop, we cover the fundamentals, including the markdown syntax, code chunks and inline code, and the output formats available. We also go over citations, cross-referencing, and templating, which ultimately allow you to write academic papers entirely in Quarto.</p><p><br>The self-paced tutorial for this workshop can be found here: <a href="https://lmu-osc.github.io/introduction-to-Quarto/">https://lmu-osc.github.io/introduction-to-Quarto/</a></p><p>The self-paced tutorials focus on using Quarto with R and RStudio, which is also used by the instructors in their research and teaching. They are, however, no experts for every possible environment, but will try their best to assist you.</p><p><strong>Participants</strong>: The targeted audience are total novices or intermediate users of literate programming tools (e.g. Rmarkdown, Quarto), who program (at any level) in R, Python, or Julia, and preferentially use RStudio (although VS Code, Jupyter, Neovim or other text editor are also suitable). Ideally, participants already know of or use version control.</p><p><strong>Requirement</strong>: Participants must have their own laptop with admin access. Software will be installed as part of the workshop.</p><p>The event will be held in English. </p><div class="g-clear"></div>



 
