---
title: Auftaktveranstaltung
categories: ReproducibiliTea Journal Club
event:
  card_description: ''
  start_date: '2024-04-23'
  end_date: ''
  time: ''
  description: ''
  location:
    name: LMU Open Science Center (Giselastr.)
    address: Leopoldstraße 13, Room 3322, 80802 Munich
    map_url: https://www.google.com/maps/place/Ludwig-Maximilian-Universit%C3%A4t+M%C3%BCnchen/@48.1559372,11.5833416,19.19z/data=!3m1!5s0x479e75bf863d5581:0x29d36540810c2590!4m6!3m5!1s0x479e75c07933e683:0x4851cac28ba68cb4!8m2!3d48.1558072!4d11.5829777!16s%2Fg%2F1hc2d61v7?entry=ttu&g_ep=EgoyMDI2MDUyMC4wIKXMDSoASAFQAw%3D%3D
    type: In-Person
    detail: ''
  language:
    primary: German
    primary-code: de
    detail: ''
links:
  registration: ''
  materials: ''
  workshop_website: ''
instructors:
  - name: ''
    url: ''
helpers:
  - name: ''
contact:
  name: ReproducibiliTea
  email: reproducibilitea.munich@gmail.com
organizers:
  - name: Laura Goetz
    url: ''
  - name: Viktoria Wiegelmann
    url: ''
  - name: Gracia Prüm
    url: ''
  - name: Finia Loeb
    url: ''
  - name: Alp Kaan Aksu
    url: ''
  - name: Julian Lange
    url: ''
host:
  - name: ReproducibiliTea Team
    url: ''

template: templates/event-template.html
filters:
    - templates/process-event-yaml.lua
---

<br>

 

<p>Zum Start in das neue Semester möchte der ReproducibiliTea Journal Club euch gerne zu unserer Auftaktveranstaltung einladen. Nutzt die Gelegenheit, um mehr über unseren Journal Club zu erfahren und gleichzeitig neue Kontakte zu knüpfen. Wir freuen uns darauf, viele neue Gesichter zu sehen!</p><p><strong>Ablauf: </strong>Zu Beginn der Sitzung habt ihr die Möglichkeit mehr über unseren Journal Club und das Semesterprogramm zu erfahren. Danach habt ihr Zeit, euch bei Tee und Keksen kennenzulernen und zu vernetzen. </p><p><strong>Über den Journal Club: </strong><a href="https://www.osc.lmu.de/partners/local-os-initiatives/reproducibilitea.html">Hier</a> findet ihr mehr Informationen über das Konzept des Journal Clubs.</p><p>Ihr seid herzlich eingeladen, an unseren kommenden Treffen teilzunehmen! Um auf dem Laufenden zu bleiben und Benachrichtigungen über unsere Sessions und die ausgewählten Artikel zu erhalten, könnt ihr unsere Mailingliste abonnieren, entweder indem ihr auf den folgenden Link klickt, <a href="https://lists.lrz.de/mailman/listinfo/reproducibilitea">https://lists.lrz.de/mailman/listinfo/reproducibilitea</a>, oder indem ihr uns eine E-Mail an <a class="g-link-mail" href="mailto:reproducibilitea.munich@gmail.com" title="Send email to: reproducibilitea.munich@gmail.com">reproducibilitea.munich@gmail.com</a> schreibt. Es ist nicht erforderlich, das behandelte Paper vor jeder Sitzung gelesen zu haben, es könnte allerdings von Vorteil sein.</p><p>Wir freuen uns, euch bei einer unserer nächsten Journal-Club-Sitzungen zu sehen!</p><p>organizationsteam:</p><ul style="list-style-type: square;">
<li>Laura Goetz, Studentin in Medizin und Masterstudentin in Psychologie</li>
<li>Viktoria Wiegelmann, Bachelorstudentin in Psychologie</li>
<li>Gracia Prüm, Bachelorstudentin in Psychologie</li>
<li>Finia Loeb, Bachelorstudentin in Psychologie</li>
<li>Alp Kaan Aksu, Bachelorstudent in Psychologie und Informatik</li>
<li>Julian Lange, Doktorand in Statistik</li>
</ul>
<p> </p><div class="g-clear"></div>



 
