---
title: Software Carpentry - R Flavored - Mensa Leopoldstraße
categories: Workshop
date: '2024-10-10'
event:
  title: Software Carpentry - R Flavored - Mensa Leopoldstraße
  description: ''
  date: '2024-10-10'
  end_date: '2024-10-11'
  time: ''
  location:
    name: Mensa Leopoldstr 13A, room 046
    address: ''
    map_url: ''
  format:
    type: Workshop
    detail: ''
  language:
    primary: English
    primary-code: en
    detail: ''
links:
  registration: ''
  materials: ''
  workshop_website: ''
event_description: ''
instructors:
  - name: Alberto Villagran Asiares
    url: ''
  - name: Alp Kaan Aksu
    url: ''
  - name: Renata Topinkova
    url: ''
  - name: Po-chun Tseng
    url: ''
helpers:
  - name: ''
contact:
  name: Malika Ihle
  email: malika.ihle@lmu.de
organizers:
  - name: Dr. Malika Ihle
    url: ''
host:
  - name: LMU Open Science Center
    url: ''
  - name: Munich Center for Machine Learning (MCML)
    url: ''

---
<!-- MANDAORY SECTION START  -->

{{< include templates/_setup.qmd >}}
{{< include templates/_info_boxes.qmd >}}
{{< include templates/_register_button.qmd >}}
<!-- MANDAORY SECTION END  -->

<br>

<!-- DETAILED EVENT DESCRIPTION HERE OR USE THE TEMPLATE BELOW TO INCLUDE THE STANDARD DESCRIPTION SECTION -->
<!-- {{< include templates/_event_description.qmd >}} -->

<p>In this Software Carpentry Workshop you will learn the <strong>Unix Shell, Git and R</strong>.</p><p>This example-driven <strong>two-day workshop</strong> will teach core computing skills that will help you be more productive and effective. We'll alternate short tutorials with hands-on practical exercises. Participants are encouraged to help one another and to apply what they are learning to their own research problems during the workshop.</p><p>See the workshop website for <strong>more details</strong>: <a href="https://lmu-osc.github.io/2024-10-10-LMU-Leo/">https://lmu-osc.github.io/2024-10-10-LMU-Leo/</a></p><p><strong>Instructors:</strong>  Alberto Villagran Asiares, Alp Kaan Aksu, Renata Topinkova, Po-chun Tseng</p><p>Registration is mandatory, and participation requires setting up the software in advance by following the provided instructions (a help desk session will also take place the day prior to the workshop). Please register only if you are available for the whole course.</p><ul style="list-style-type: square;"><li>
</li></ul>
<div class="g-clear"></div>



<!-- MANDAORY SECTION START  -->
<!-- _event_description.qmd template should always be at bottom -->
{{< include templates/_instructors_helpers_contact.qmd >}}
<!-- MANDAORY SECTION END  -->
