---
title: "1. Plan & Design"
description: "Explore existing resources, check legal requirements, write data management plans, design studies, and prepare preregistrations"
body-class: orc-phase-1
phase_order: 1
sidebar: training
number-depth: 4
number-sections: true
number-offset: [0,1,0]
page-layout: full
toc: false
css: handbook-styles.css
title-block-style: none
anchor-sections: true
---


```{=html}
<style>


.accordion-button {
    pointer-events: none;
}

.accordion-button::after {
    pointer-events: all;
}

</style>
```




::: {.accordion #accordionExample}
::: {.accordion-item}

::: {.accordion-button type="button" data-bs-toggle="collapse" data-bs-target="#collapseOne" aria-expanded="true" aria-controls="collapseOne"}

### Accordion Item #1 {#sec-accordion-item-1}


:::

::: {#collapseOne .accordion-collapse .collapse .show data-bs-parent="#accordionExample"}

::: {.accordion-body}
[**This is the first item’s accordion body.**]{}

It is shown by default, until the collapse plugin adds the appropriate classes that we use to style each element. These classes control the overall appearance, as well as the showing and hiding via CSS transitions.

You can modify any of this with custom CSS or overriding our default variables. It’s also worth noting that just about any HTML can go within the `[.accordion-body]{.code}`.

:::{.panel-tabset}

#### Tab 1 {#sec-tab-1}

some content here

#### Subsection 1.1 {#sec-subsection-1-1}

some more content here

#### Subsection 1.2 {#sec-subsection-1-2}

some more content here


:::

:::

:::
:::
:::


#### Header outside of the accordion {#sec-header-outside-accordion}









::: {.accordion #accordionExample}
::: {.accordion-item}

::: {.accordion-button type="button" data-bs-toggle="collapse" data-bs-target="#collapseTwo" aria-expanded="true" aria-controls="collapseTwo"}

### Accordion Item #2 {#sec-accordion-item-2}


:::

::: {#collapseTwo .accordion-collapse .collapse .show data-bs-parent="#accordionExample"}

::: {.accordion-body}
[**This is the second item’s accordion body.**]{}

It is shown by default, until the collapse plugin adds the appropriate classes that we use to style each element. These classes control the overall appearance, as well as the showing and hiding via CSS transitions.

You can modify any of this with custom CSS or overriding our default variables. It’s also worth noting that just about any HTML can go within the `[.accordion-body]{.code}`.

:::{.panel-tabset}

#### Tab 2 {#sec-tab-2}

some content here

#### Subsection 2.1 {#sec-subsection-2-1}

some more content here

#### Subsection 2.2 {#sec-subsection-2-2}

some more content here


:::

:::

:::
:::
:::





