---
title: "A portrait of the LMU Open Science Center"
date: 2018-07-27
subtitle: "LMU‘s interdisciplinary Open Science Center (OSC) was formally inaugurated on May 8 2018. Its aim is to make scientific research more transparent and to strengthen its self-correcting mechanisms by facilitating the replication of published work. Here's a portrait of the OSC."
categories: ["Events"]
---


<p><em>[This is an updated English version of the LMU's original <a href="https://www.uni-muenchen.de/aktuelles/news/2018/open_science_center.html">press release</a>]</em></p>
<p>The OSC’s mission statement underlines the fact that good scientific practice sets high standards for researchers. Among others, published research needs to be transparent and reproducible. This means that all research processes must be reported in sufficient methodological detail to allow other appropriately trained scientists to repeat them and verify their conclusions. This requires the application of open science standards, such as the preregistration of study designs and the provision of open access to the study data and material. The OSC’s primary goal is to foster these standards by strengthening interdisciplinary expertise andmaking young researchers aware of the need for transparency and reproducibility. Achieving these goals will in turn require detailed studies of research practices and replication processes in various disciplines, continuing education of qualified researchers in these areas and convincing grant agencies and other relevant institutions of the need to promote openness in science.</p>
<p>The creation of the Open Science Center is a central part of LMU‘s commitment to fostering best practices in scientific research. “For a university of excellence, the establishment of such a center is a highly pertinent and very welcome step,” says Professor Barbara Conradt, Vice-President for Research and Diversity. The OSC’s Spokesperson, LMU sociologist Professor Katrin Auspurg, underlines the Center’s importance: “We need institutions that are committed to the ideals of open science, work to develop consistent standards, carry out research on replicability, increase the general awareness of the issue, and ensure that the organizations involved in the research enterprise take due cognizance of its significance. The relentless competition for resources, funding, and faculty positions should not tempt researchers to focus on areas that are guaranteed to make headlines or to publish as much, as quickly, and as prominently as possible. They must also focus on quality control, on reliability and reproducibility, and ensure that their procedures are transparent and accessible to others in their field. The OSC will take on a pioneering role in this respect, by exploring ways to improve research practices and strengthen trust in the scientific enterprise as a whole.”</p>
<h3>Goals of the OSC</h3>
<p>The new Center has chosen to focus on three major goals. The first is to train researchers in Open Science skills and to increase the students’ and junior researchers’ awareness for good scientific practice. This will be done by providing workshops, informal conferences, and other training modules.</p>
<p><br>Secondly, the Center will make the scientific process the subject of research– in other words, conduct research on the research process. Here, the idea is to explore the psychological, sociological, statistical, and methodological aspects of scientific procedures, which can lead to erroneous or biased research results.</p>
<p>Finally, the OSC plans to act as a think tank and to instigate a reform of incentive structures that mold the modern-day practice of research and science: Scientific publication standards as well as criteria for the evaluation of researchers in faculty search and grant application procedures should incentivize good scientific practice. “It is vital to take a closer look at the quality and replicability of research,” says psychologist Dr. Felix Schönbrodt, the Center’s Managing Director, who was also closely involved in its conception and design. “The Open Science Center signals our commitment to a program. We committed to integrity and dependability, and we seek to impart these values in our teaching, in our recruitment policies, in our activities as reviewers, and – above all – in our day-to-day practice as researchers.” Among other things, this will enhance the University’s long-term competitiveness. “For example, in the context of research funding by the EU, and with the establishment of the new Open Research Funders Group, the issue of open science will in future play a central role in determining the approval of grants for proposed research projects.”</p>
<h3>An interdisciplinary focus</h3>
<p>The OSC is an unequivocally interdisciplinary enterprise. Its 35 members [as of July 2018] represent 11 different areas of study, ranging from sociology to informatics and geography. The Faculties of Medicine, Veterinary Medicine, and Psychology and Education have all joined the new venture, as well as the LMU-ifo Economics &amp; Business Data Center. In addition, the OSC’s work will be supported by the Leibniz Supercomputing Center (LRZ) and the University Library.</p>
<p>The idea has aroused great interest at LMU. “We have approached lots of people and the response has been unexpectedly enthusiastic,” says Schönbrodt, and he goes on to point out the great promise of open science for its practitioners. “Adherence to the tenets of Open Science improves the planning, execution and analysis of research studies and facilitates their publication and it helps to counteract biases before they become actionable”.</p>
<p>The Center will also provide a forum for the publication of negative results and replication studies. And although this type of work is said to be less spectacular than primary studies that report new findings, it is essential as a test of the robustness and validity of published claims. “Seen in this light, open science offers researchers a valuable tool in the quest for well-founded and trustworthy insights into the world around us.”</p>
<div class="g-clear"></div>
