---
title: "Open Science Toolbox"
date: 2018-05-16
subtitle: "Take a look at our new Open Science Toolbox! We offer a collection of helpful links to tools and resources that researchers can use to make their research more transparent and reproducible."
categories: ["Announcement"]

template: templates/news-template.html
filters:
  - templates/process-news-yaml.lua
---


<p>How exactly can I make my research more transparent? What software can I use? How do I find Open Access journals? Where do I find practical resources on specific Open Science practices? Where do I find workshop material for teaching Open Science?</p>

<p>In order to close the intention-action gap concerning Open Science practices, we created a collection of resources and tools that can be implemented in a transparent and reproducible research process. As a researcher you can look for resources for every stage of the research process. If you want to teach Open Science or participate in a course yourself, you'll find examplary workshop material, too.</p>
<p>Take a look at our new <a href="https://osf.io/zjrhu/files/mwng8" title="Toolbox"><strong>Open Science Toolbox</strong></a> and don't hesitate to give feedback and suggestions.</p>
<div class="g-clear"></div>
