---
title: "Open Social Science Conference (@opensocsci): Jan 2019"
date: 2018-07-30
subtitle: "The LMU Open Science Center is official partner of the Open Social Science Conference (@opensocsci) in Mannheim. Want to contribute? Submission deadline for abstracts is Aug. 22, 2018."
---


<p>From the <a href="https://www.mzes.uni-mannheim.de/openscience/">conference webseite:</a></p>
<h3>Practicing New Standards in Transparency and Reproducibility</h3>
<p class="hinterlegt">About a decade ago, John Ioannidis claimed that “most published research findings are false”. While seeming outrageous at the time, a growing body of meta-scientific research in the behavioral and social sciences has since substantiated this claim, causing uncertainty about the trustworthiness of published scientific findings. We believe that threats to the validity of published findings in the social sciences are widespread and systemic. Therefore, this conference promotes introspection about the current state of social science research and exchange on the opportunities for institutional and methodological improvement in the future. It is interdisciplinary in nature. Scholars working in any branch and within any methodology of the social sciences are invited to attend. The conference is supported by the Berkeley Initiative for Transparency in the Social Sciences (BITSS) and will take place from 25-27 January 2019 at the Mannheim Centre for European Social Research (MZES) in Mannheim, Germany.</p>
<p> </p>
<div class="g-clear"></div>
