---
title: "Open Science in der Promotion"
date: 2019-11-25
subtitle: "An event from the series "Kurz & bündig" of the GraduateCenterLMU"
---

NA

<p>We are glad to announce an event from the series "Kurz &amp; bündig" of the GraduateCenterLMU</p>
<p>In discussions about the quality of scientific work, the term "Open Science" has been appearing again and again for several years. What does this term mean, and why should doctoral students deal with it as part of their research project?</p>
<p><br>Topics:</p>
<ul style="list-style-type: square;">
<li>"Everything new and everything different? - Origin and Location of Open Science</li>
<li>Fields of action - central topics of Open Science</li>
<li>The actors - the LMU Open Science Center and other institutions</li>
<li>"And what does that have to do with my dissertation?" - Discussion of possible challenges for one's own research activities</li>
</ul>

<p class="hinterlegt">When: 25.11.2019, 4 pm (s.t.) to 6pm<br>Where: LMU Munich, Room announced after registration<br>Language: German<br>Target group: PhD candidates of the LMU (number of participants is limited)<br>Contact: <a class="g-link-mail" href="mailto:graduatecenter@lmu.de" title="Send email to: graduatecenter@lmu.de">graduatecenter@lmu.de</a> (phone: 089/2180-9732)</p>
<p><br><a href="https://www.graduatecenter.uni-muenchen.de/veranstaltungen/kurzbuendig/open_science/index.html">Registration for the workshop</a><br><a>Frequently Asked Questions (short &amp; concise)</a></p>
<div class="g-clear"></div>
