---
title: "Joint OSC symposium"
date: 2019-03-20
subtitle: "Computational Statstics and Statistical Software III Symposium on the DAGStat Conference 2019"
categories: ["Events"]
---


<p>Since Monday, March 18th, the <a href="https://www.dagstat2019.statistik.uni-muenchen.de/index.html">DAGStat Conference 2019</a> has been taking place in Munich with the motto "Statistics under one umbrella". Accordingly, we contributed a joint OSC symposium "Computational Statistics and Statistical Software III (Open science and reproducibility)". Each talk and a link to the respective slides can be found in the following overview:</p>
<table class="table" border="0"><tbody>
<tr>
<td><strong>Time</strong></td>
<td><strong>Talk</strong></td>
</tr>
<tr>
<td>09:00 am – 09:20 am</td>
<td>
<strong>Open Science and statistics</strong><br><em>Anne-Laure Boulesteix</em><br>slides: <a href="https://osf.io/u2zbc/">https://osf.io/u2zbc/</a>
</td>
</tr>
<tr>
<td>09:20 am – 09:40 am</td>
<td>
<strong>Research Software Engineers</strong><br><em>Heidi Seibold<br></em>slides: <a href="https://osf.io/eaj6m/">https://osf.io/eaj6m/</a>
</td>
</tr>
<tr>
<td>09:40 am – 10:00 am</td>
<td>
<strong>Reproducible Methodological Research and Scientific Publishing</strong><br><em>Fabian Scheipl<br></em>slides: <a href="https://osf.io/5ahkb/">https://osf.io/5ahkb/</a>
</td>
</tr>
<tr>
<td>10:00 am – 10:20 am</td>
<td>
<strong>Correcting for bias in the literature: A comparison of metaanalytic methods for bias-correction</strong><br><em>Felix D. Schönbrodt<br></em>slides: <a href="https://osf.io/hkyrx/">https://osf.io/hkyrx/</a>
</td>
</tr>
<tr>
<td>10:20 am – 10:40 am</td>
<td>
<strong>The multiplicity of possible analysis strategies and how it is </strong><strong>handled across scientific disciplines<br></strong><em>Sabine Hoffmann<br></em>slides: <a href="https://osf.io/ykbux/">https://osf.io/ykbux/</a>
</td>
</tr>
</tbody></table>

<p> Thank you very much for coming!<br><br> <br><br><br><br></p>
<div class="g-clear"></div>
