---
title: "Open Science experts invited to the Berlin regional parliament"
date: 2020-11-02
subtitle: "Discussion on the proposal "Strengthen good scientific practice and scientific integrity: Establish an interdisciplinary network office for Open Science and Research Quality""
---

NA

<p>The committee for science and research of the Berlin regional parliament invited six experts for Open Science to speak about a current proposal for a new Open Science office in Berlin. The statements included interesting political suggestions and topics around Open Science and the replications crisis in the social sciences. For instance, the importance of incentive structures in science (e.g. appointment committees), methodological education for students, and the collaboration between different Open Science stakeholders in Europe (e.g. <a href="http://www.open-access-berlin.de/index.html">Open Access Office Berlin</a>, <a href="https://www.eosc-portal.eu/">European Open Science Cloud</a>, <a href="https://osf.io/tbkzh/#!#!">Network of Open Science Initiatives (NOSI)</a>) was highlighted. Furthermore, the experts described the Berlin history of existing institutions (e.g. <a href="http://www.open-access-berlin.de/index.html">Open Access Office Berlin</a>) and actions (e.g. <a href="https://openaccess.mpg.de/67605/berlin_declaration_engl.pdf">Berlin Declaration</a>) towards more transparency in science. Subsequently, the specific contents of the proposal (e.g. involvement of university libraries, responsibilities between politics and science) were discussed further by the politicians and related questions were asked to the experts. The recorded meeting gives an interesting overview of present political topics around Open Science.</p>
<p>Link to the recorded meeting:<br><a href="https://www.youtube.com/watch?v=Fo7GP95Fs2w&amp;list=PLgqUxMeOmFHz3dxbD-zR7kbuaJbeB9SWD&amp;index=2">https://www.youtube.com/watch?v=Fo7GP95Fs2w&amp;list=PLgqUxMeOmFHz3dxbD-zR7kbuaJbeB9SWD&amp;index=2</a><br>Language: German</p>
<p>Open Science session starting at 00:23:52<br>Ending at 2:15:44</p>
<h2>Schedule</h2>
<ol>
<li>Introduction to the consultation starting at 00:23:52</li>
<li>Introduction to the proposal for a new Open Science network in Berlin starting at 00:27:08</li>
<li>Statements of the experts starting at 00:34:38</li>
<li>Discussion/Questions to the experts starting at 01:18:17</li>
<li>Answers from the experts starting at 01:40:31</li>
<li>Introduction to previous Open Science strategy in Berlin starting at 02:13:14</li>
</ol>

<p>Featuring:</p>
<ul style="list-style-type: square;">
<li>Dr. Christoph Bruch (<a href="https://os.helmholtz.de/">Helmholtz Open Science Office</a>) - statement starting at 00:34:38 - answers starting at 01:40:31</li>
<li>Alexander Czmiel (<a href="https://www.bbaw.de/en/bbaw-digital/telota">TELOTA-Team of Berlin-Brandenburg Academy of Sciences and Humanities</a>) - statement starting at 00:39:10 - answers starting at 01:45:42</li>
<li>Prof. Dr. Ulrich Dirnagl (<a href="https://www.bihealth.org/de/forschung/quest-center/">QUEST</a>, Charité) - statement starting at 00:46:00 - answers starting at 01:49:07</li>
<li>Prof. Dr. Kai Horstmann (HU Open Science Initiative) - statement starting at 00:51:49 - answers starting at 01:54:22</li>
<li>Maxi Kindling (<a href="http://www.open-access-berlin.de/index.html">Open Access Office Berlin</a>, FU Berlin) - statement starting at 00:59:21 - answers starting at 02:01:23</li>
<li>Prof. Dr. Dirk Ostwald (<a href="https://www.fu-berlin.de/sites/open-science/index.html">Open Science Working Group FU Berlin</a>) - statement starting at 01:09:31 - answers starting at 02:07:28</li>
</ul>

<div class="g-clear"></div>
