---
title: "OSC has been awarded the title of 'Hochschulperle' ('University Pearl') by the Stifterverband"
date: 2020-03-09
subtitle: "NA"
---

NA

<p><em>[This is a translation of the LMU <a href="https://www.uni-muenchen.de/aktuelles/preise/2020/hochschulperle.html">press release</a>]<br></em></p>
<p><em>The LMU's Open Science Center strengthens the commitment to open, transparent and replicable research. Its interdisciplinarity and breadth of expertise make it the first university center of its kind. <a href="https://www.stifterverband.org/hochschulperle">It has now been awarded the title of "University Pearl" by the Stifterverband.</a></em></p>
<p>Since science is under particular competitive pressure today, it is all the more important to ensure its quality and credibility and to promote transparency - also institutionally. The Open Science Center (OSC) of the Ludwig-Maximilians-Universität Munich pursues this approach and even starts with the students. "Especially in times when medical and social challenges require particularly scientifically sound answers, we need open, cooperative and credible science. The award of the Stifterverband is a wonderful confirmation of our approach to promote the reproducibility and traceability of scientific results," says Dr. Felix Schönbrodt, managing director of the OSC.</p>
<p>The OSC was founded at the LMU in 2018 and has since then been working on three main areas: On the one hand, it wants to train young scientists as well as established researchers with workshops, conferences and other events on Open Science and sensitize students to the topic. Secondly, it wants to explore the scientific process itself. In doing so, the researchers are specifically investigating psychological, sociological and statistical-methodological aspects that can lead to distorted or incorrect research results. And finally, the OSC wants to make the incentive structures in the academic system a topic of discussion and to develop recommendations and proposals for relevant bodies. The OSC is particularly interdisciplinary in its approach; its members come from fifteen different disciplines - ranging from sociology to computer science and medicine.</p>
<p>The jury of the Stifterverband (Donors' Association for the Promotion of Sciences and Humanities in Germany) stated in its justification for the award as a university pearl: "With its comprehensive approach to Open Science, which ranges from training to incentive structures, the Open Science Center at LMU Munich opens up a large target group of students and researchers. The project promotes Open Science at all levels and also addresses current debates on Open Science and Open Data". The Stifterverband awards the "University Pearl" prize to innovative projects at universities. In 2020, the award will have the overall theme of "Open Science".</p>
<div class="g-clear"></div>
