---
title: "Data tracking in research: Aggregation and use or sale of usage data by academic publishers"
date: 2021-06-15
subtitle: "German Research Foundation issued a briefing paper
about the digital tracking of researchers by academic
publishers"
categories: ["Reports"]
---


<p>According to recent<a href="https://www.dfg.de/en/research_funding/programmes/infrastructure/lis/awbi/"> briefing paper issued by the German Research Foundation</a>, there is a risk that the shift in the commercial business model towards data analytics will result in the knowledge society becoming privatised. Ultimately, it might no longer be the public sector but increasingly private companies that are privy to knowledge about research content and trends, its institutions and stakeholders.</p>
<p>Potentially, research tracking of this kind can fundamentally contradict academic freedom and informational self-determination. It can endanger scientists and hinder the freedom of competition in the field of information provision. For this reason, scholars and academic institutions must become aware of the problem and clarify the legal, technical and ethical framework conditions of their information supply. This would not only help to avoid involuntarily violating applicable law, but also ensure that academics are appropriately informed and protected.</p>
<p>There is a petition by a group of scientists called <a href="https://stoptrackingscience.eu">"Stop tracking Science"</a> against this data tracking by privat companies that hundreds of researchers have already signed to stand up against this threat to academic freedom. The OSC supports the demands of the petition and calls for its support.</p>
<h2>More information on the topic</h2>
<ul style="list-style-type: square;">
<li><a href="https://zeitung.faz.net/faz%20/geisteswissenschaften/2021-05-26/276e8404c41a1bbca09960cbd628341f/?GEPC=s5">Recent comment in the German newspaper "Frankfurter Allgemeine"</a></li>
<li><a href="https://elephantinthelab.org/when-your-journal-reads-you/">Blog post by Renke Siems</a></li>
</ul>

<div class="g-clear"></div>
