---
title: "Election of the 'Hochschulperle' ('University Pearl') of the Year 2020 by the Stifterverband"
date: 2021-01-21
subtitle: "OSC as one of the monthly winners"
---


<p>In March 2020, the <a href="../hochschulperle/index.html" title='OSC has been awarded the title of "Hochschulperle" ("University Pearl") by the Stifterverband'>Open Science Center (OSC) was awarded the title "University Pearl"</a> by the Stifterverband. Each month another project had been honoured. Now, the Stifterverband awarded the title of "University Pearl 2020" to the winning project "Courage and civil courage in democracy", supporting it with a prize of 3000€ . There was an open election between all twelve monthly winners of 2020 which took place between January 20th 2021, 12am, and January 21st 2021, 12am. All information about the election results can be found at the <a href="https://www.stifterverband.org/hochschulperle/2020">homepage of the "University Pearl"</a>. There you can also find short presentations of all projects awarded the monthly title "University Pearl" within last year’s competitions. In 2020, the award had the overall theme of "Open Science". Interesting institutions and projects were awarded alongside the OSC.</p>
<p>The high number of 3157 voters shows that open science matters!</p>
<h2>About the LMU Open Science Center</h2>
<p>The LMU's Open Science Center strengthens the commitment to open, transparent and replicable research. Its interdisciplinarity and breadth of expertise make it the first university center of its kind. If you vote for the OSC you would support its goals and help to keep the members working on the wide range of the following projects which might have gained even more importance during the covid-19-crisis:</p>
<p>The OSC was founded at the LMU in 2018 and has since then been working on three main areas: On the one hand, it wants to train young scientists as well as established researchers. Therefore, it organises workshops, conferences, talks and other events on Open Science and sensitize students to the topic. Secondly, it wants to explore the scientific process itself. In doing so, the scientific members are specifically investigating psychological, sociological and statistical-methodological aspects that can lead to distorted or incorrect research results. And finally, the OSC wants to make the incentive structures in the academic system a topic of discussion and to develop recommendations and proposals for relevant bodies. The OSC is particularly interdisciplinary in its approach; its members come from fifteen different disciplines - ranging from sociology to computer science and medicine.</p>
<p>Since science is under particular competitive pressure today, it is all the more important to ensure its quality and credibility and to promote transparency - also institutionally. The Open Science Center (OSC) of the LMU Munich pursues this approach and starts right away with the students. "Especially in times when medical and social challenges require particularly scientifically sound answers, we need open, cooperative and credible science. The award of the Stifterverband is a wonderful confirmation of our approach to promote the reproducibility and traceability of scientific results," said Dr. Felix Schönbrodt, managing director of the OSC, after winning the monthly award.</p>
<p>The jury of the Stifterverband (Donors' Association for the Promotion of Sciences and Humanities in Germany) stated in its justification for the monthly award as a university pearl: "With its comprehensive approach to Open Science, which ranges from training to incentive structures, the Open Science Center at LMU Munich opens up a large target group of students and researchers. The project promotes Open Science at all levels and also addresses current debates on Open Science and Open Data". The Stifterverband awards the "University Pearl" prize to innovative projects at universities.</p>
<div class="g-clear"></div>
