---
title: "Stellenausschreibung: Open Science Koordinator*in"
date: 2021-11-21
subtitle: "von 02/2022 bis 12/2024 - Bewerbungsschluss 21.11.2021!"
---


<p>Am LMU Open Science Center ist zum 1.2.2022 eine befristete Stelle (Umfang 50% oder 100%) als</p>
<p><strong>Open Science Koordinator*in (m/w/d; E13 TV-L)</strong></p>
<p>zu besetzen. Die Stelle ist zunächst bis Dezember 2024 befristet; eine Verlängerung wird vorbehaltlich der Finanzierung angestrebt. Das LMU Open Science Center (OSC) ist eine fakultätsübergreifende Einrichtung der Ludwig-Maximilians-Universität (LMU), mit der Aufgabe, Open-Science-Praktiken an der LMU München und darüber hinaus zu fördern und mit meta-wissenschaftlicher Forschung zu untersuchen. Darüber hinaus strebt das OSC an, die Einführung offener Wissenschaftspraktiken auch durch die Etablierung entsprechender Anreizstrukturen in der Wissenschaft zu fördern (etwa Anreize für Replikationen und transparente Forschung; Erhöhung der Reputation für offene, replizierbare Forschung).<br>Arbeitssprachen am OSC sind Deutsch und Englisch, verhandlungssichere Deutschkenntnisse werden erwartet.</p>
<p><strong>Ihre Aufgaben:</strong></p>
<p>Sie sind für die wissenschaftliche und organisatorische Koordination sowie Unterstützung von Vorstand und Geschäftsführer des LMU Open Science Centers verantwortlich. Das beinhaltet insbesondere:</p>
<ul>
<li>Ein aktives, gestaltendes Einbringen bei der Curriculums-/Strategieentwicklung zur Einbindung und Förderung von Open Science an der LMU und darüber hinaus</li>
<li>Unterstützung von Forschungskooperationen in Bezug auf Open-Science-Aspekte</li>
<li>Organisation von Kolloquien und Workshops, Einladung und Betreuung von Referent:innen</li>
<li>Organisation von Aktivitäten wie einem regelmäßigen Open Science-Tag an der LMU</li>
<li>Vernetzung von verschiedenen Stellen innerhalb der LMU (z.B. OSC, Bibliothek, Forschungsförderung, LRZ, Fakultäten)</li>
<li>Mitarbeit an Finanzierungskonzepten</li>
<li>Betreuung der Webseite</li>
<li>Wünschenswert: Die Übernahme von Lehre am Lehrstuhl für Psychologische Methodenlehre und Diagnostik am Department Psychologie der LMU (Umfang abhängig vom Stellenumfang; max. 5 SWS)</li>
</ul>

<p><strong>Insbesondere bei einer 100%-Stelle wünschen wir uns zusätzlich:</strong></p>
<ul>
<li>Durchführung von eigenen Workshops</li>
<li>Erfahrung mit Drittmittelakquise und Antragstellungen</li>
<li>Vernetzung mit verschiedenen Stellen und Institutionen außerhalb der LMU (z.B. Open-Science-Initiativen, Fachgesellschaften, Ministerien)</li>
</ul>

<p><strong>Voraussetzungen:</strong></p>
<ul>
<li>Abgeschlossenes wissenschaftliches Hochschulstudium (mindestens Master oder vergleichbar; vorzugsweise Promotion)</li>
<li>Open Science-Affinität</li>
<li>Sehr gute Kenntnisse wissenschaftlicher Arbeitsmethoden und -techniken</li>
<li>Teamfähigkeit</li>
<li>Sehr gute Organisationsfähigkeit</li>
<li>Versierter Umgang mit IT</li>
</ul>

<p>Die LMU strebt eine Erhöhung des Anteils der Frauen in Forschung und Lehre an und bittet deshalb Wissenschaftlerinnen nachdrücklich, sich zu bewerben. Schwerbehinderte werden bei ansonsten im Wesentlichen gleicher Eignung bevorzugt.</p>
<p>Bitte schicken Sie Ihre Bewerbung mit aussagekräftigen Unterlagen <strong>bis zum 21.11.2021</strong> ausschließlich in digitaler Form als <em>ein</em> PDF-Dokument an <a href="mailto:sek.auspurg@soziologie.uni-muenchen.de">sek.auspurg@soziologie.uni-muenchen.de</a> (Sekretariat), mit dem Betreff „Bewerbung Open Science Koordination“. Bitte fügen Sie die üblichen Unterlagen bei (Lebenslauf, wenn zutreffend mit Schriftenverzeichnis) und erläutern Sie im Anschreiben, welche Bezüge und Erfahrungen Sie bereits zum Thema „open science“/ reproduzierbarer Forschung gemacht haben. Es ist geplant, die Auswahlgespräche vom 1.12.2021 bis 3.12.2021 durchzuführen.</p>
<p>Für Rückfragen steht Ihnen Prof. Dr. Felix Schönbrodt per E-Mail unter<a href="mailto:felix.schoenbrodt@psy.lmu.de"> felix.schoenbrodt@psy.lmu.de</a> zur Verfügung.</p>
<p>Im Rahmen Ihrer Bewerbung auf eine Stelle an der Ludwig-Maximilians-Universität München (LMU) übermitteln Sie personenbezogene Daten. Beachten Sie bitte hierzu unsere Datenschutzhinweise gemäß Art. 13 Datenschutz-Grundverordnung (DSGVO) zur Erhebung und Verarbeitung von personenbezogenen Daten und die Datenschutzerklärung der LMU für den Internetauftritt. Durch die Übermittlung Ihrer Bewerbung bestätigen Sie, dass Sie die Datenschutzhinweise und die Datenschutzerklärung zur Kenntnis genommen haben und mit der Datenverarbeitung im Rahmen des Auswahlverfahrens einverstanden sind.</p>
<p> </p>
<div class="g-clear"></div>
