---
title: "The LMU Open Science Center joined the German Reproducibility Network!"
date: 2022-10-18
subtitle: "NA"
---

NA

<p>The <a href="https://reproducibilitynetwork.de">German Reproducibility Network</a> (GRN) is a multidisciplinary consortium that aims to increase transparency and trustworthiness of scientific research. The Network’s goals are to promote open research practices through training and community building, to conduct meta-research, and to work with stakeholders across the sector to ensure coordination of efforts at the national level. The GRN was established in 2021 and includes institutional members and a network of grassroots initiatives.</p>
<p>Sharing the same goals, at the local level, the LMU Open Science Center has, since 2017, already made substantial contributions to promote open research practices (ORPs) across disciplines, at LMU Munich and beyond. The OSC onboards institutional (e.g. university departments) and individual members who commit to actively support the goals of the OSC. The Center organises workshops, seminars, conferences, panel discussions, and courses at the LMU; curates public online resources; coordinates local grassroots initiatives (e.g. Open Science Initiative in Psychology, in Medicine, in Statistics, and Reproducibility Journal Club); and serves as a forum that creates opportunities for collaboration on local meta-research projects.</p>
<p>The LMU OSC Academic Coordinator, Dr Malika Ihle, is ready to step up in the role of German Reproducibility Network Institutional Lead: “As the former Local Network Lead of the UK Reproducibility Network at the University of Oxford, I have seen what great progress such national collaboration can achieve. I’m excited to contribute to the development of a German strategic plan to improve research practices”.</p>
<p>The LMU OSC Speaker, Professor Ralf Ludwig, sees the membership with the GRN as a milestone: “Standards of good research practices are evolving, and the LMU OSC is committed to leading the way in this shift toward openness. We are excited to be part of the GRN and are looking forward to connecting with other stakeholders across the academic ecosystem so we can join our efforts and move together in the same direction.”</p>
<div class="g-clear"></div>
