---
title: "LMU Open Access Fund"
date: 2022-03-18
subtitle: "Open Access is becoming the standard publication model in the sciences."
---


<p>The University Library promotes Open Access in a variety of ways, whether through agreements with publishers that grant researchers discounts on publication fees or by providing repositories and consulting services. This is because Open Access to research results enables the rapid and worldwide dissemination of scientific findings.</p>
<p>However, this development poses financial challenges for research-intensive universities like LMU. It is therefore all the more gratifying that LMU, in collaboration with the University Library, was able to successfully place an application in the "Open Access Publication Costs" funding line of the German Research Foundation (DFG) to set up an "LMU Open Access Fund" endowed with 2.5 million euros for the years 2022 - 2024. In addition, LMU is providing 150,000 euros from its own funds for financing Open Access monographs.</p>
<p>All LMU scientists who are Corresponding Authors of a Gold Open Access article or an Open Access monograph can apply for a publication cost subsidy of up to 700 euros for articles or up to 5,000 euros for a monograph. This is intended to support the anchoring of Open Access, considering the diverse (disciplinary) publication cultures, and to go some way towards meeting financial challenges.</p>
<p>The application for the publication costs grant is made via an online platform developed by the University Library. The online application tool and further detailed information on the "LMU Open Access Fund" as well as the funding requirements can be found on the fund's website.</p>
<p><a href="https://oa-fund.ub.uni-muenchen.de">Website "LMU Open Access Fund"</a></p>
<div class="g-clear"></div>
