---
title: "Job ad: Scientific Coordinator for Open Science"
date: 2024-07-15
subtitle: "from 01/01/2025 until 31/10/2027 - Application deadline: 15.07.2024!"
---

<h2 class="g-h2 heading">Downloads</h2>
<ul class="g-ul bd">
<li class="g-pdf">
        <a href="jobad_en.pdf" target="_blank">Job ad Scientific Coordinator (English)</a>
        <span class="g-color-light g-fontsize-s">(557 KByte)</span>
</li>
        <li class="g-pdf">
        <a href="jobadgerm.pdf" target="_blank">Stellenausschreibung Wissenschaftlicher Koordinator (Deutsch)</a>
        <span class="g-color-light g-fontsize-s">(565 KByte)</span>
</li>
        </ul>

<p>The LMU Open Science Center (OSC) is seeking to fill a full-time or two part-time temporary position(s) from <strong>1st</strong> <strong>January 2025 to 31st December 2027</strong>, as:</p>
<p><strong>Scientific Coordinator for Open Science (E13 TV-L)</strong></p>
<p>The OSC is an interdisciplinary researcher-led initiative of Ludwig-Maximilians-Universität München (LMU) promoting open research practices at LMU Munich and beyond. We are seeking a highly motivated and organized Scientific Coordinator to co-lead the implementation of innovative programs funded by the Volkswagen Foundation pioneer project: <a href="https://portal.volkswagenstiftung.de/search/projectDetails.do?ref=9D211">“From local to systemic implementation: Embedding open research in institutional practices”</a>. This is a unique opportunity to drive cultural change and promote transparent and reproducible research at one of Germany's leading universities, at the feet of the Alps. Extension of the contract will be sought pending secured internal or third-party funding.</p>
<p><strong>Key Responsibilities</strong></p>
<ul>
<li>Co-develop, coordinate, and co-deliver a comprehensive open science "train-the-trainer" program at LMU and empower participants to become ambassadors for open research within their disciplines.</li>
<li>Contribute to the community engagement management of the Framework for Open and Reproducible Training (FORRT) community to coordinate the co-creation of the train-the-trainer program.</li>
<li>Collaborate with the other scientific coordinator to develop and deliver a "switch-to-open" program. This program provides tailored support to research groups of various disciplines in their transition from a closed to an open workflow, for example, by developing a written standard open research practices guide.</li>
<li>Facilitate interdisciplinary workshops, seminars, and networking events to engage and support participants in adopting open research practices.</li>
<li>Collect feedback, evaluate the program’s effectiveness, and contribute to ongoing refinement and improvement efforts.</li>
</ul>

<p><strong>Qualifications</strong></p>
<p>The ideal candidate has the following qualifications:</p>
<ul>
<li>Master's or PhD degree in any relevant field (e.g., social sciences, natural sciences, medical sciences, library science, digital humanities).</li>
<li>Familiarity with the principles of open and reproducible research.</li>
<li>Project management skills, including planning, coordination, and evaluation.</li>
<li>Ability to work independently and collaboratively in interdisciplinary teams and foster culture of inclusivity and openness.</li>
<li>Excellent communication skills, with the ability to engage and inspire diverse stakeholders.</li>
<li>English fluency is required. At equal qualifications, we will select a candidate speaking German (C1 level).</li>
</ul>

<p>Candidates with a strong willingness to learn and grow - even if they don't meet all of the listed qualifications yet - are encouraged to apply and show their potential to contribute to our team.</p>
<p><strong>What we offer</strong></p>
<p>The LMU Open Science Center was the first interdisciplinary center for open science founded at a university in Germany. The recruited candidate will have the opportunity to</p>
<ul>
<li>join an interdisciplinary team and a community of passionate open research advocates.</li>
<li>have an impact on the transparency of research in a major European university and beyond.</li>
<li>contribute to building a vibrant network of practitioners dedicated to the principles of open and reproducible research, within LMU, FORRT, and beyond.</li>
<li>have flexible home-office opportunities.</li>
</ul>

<p>Join us in driving positive change and shaping the future of academic research!</p>
<p><strong>Application process</strong></p>
<p>Interested candidates should submit a CV and cover letter, in English or in German, outlining their relevant experience and motivation for the position as a PDF to <a href="mailto:malika.ihle@lmu.de">malika.ihle@lmu.de</a>, with the subject line: ‘Application for Open Science Coordination’ by <strong>July 15</strong>. Selection interviews will take place in English from July 25 to 31 (online or in person).</p>
<p>LMU aims to increase the proportion of women in academic positions and therefore strongly encourages female scientists to apply. Disabled applicants will be given preference in the event of equal qualifications.</p>
<p>For inquiries, Prof. Dr. Felix Schönbrodt is available via email at <a href="mailto:felix.schoenbrodt@psy.lmu.de">felix.schoenbrodt@psy.lmu.de</a>.</p>
<p><br>By applying for a position at Ludwig Maximilian University Munich (LMU), you are transmitting personal data. Please refer to our data protection information according to Art. 13 of the General Data Protection Regulation (GDPR) for the collection and processing of personal data and the data protection declaration of LMU for the website. By submitting your application, you confirm that you have read and understood the data protection information and the data protection declaration and agree to the processing of data within the framework of the selection process.<br>Ludwig Maximilian University Munich is one of the best and most successful universities in Europe, with currently around 15,000 employees and approximately 52,000 students. For many years, it has been awarded the status of an excellence university and has achieved outstanding performance in research and teaching. At LMU, scientists work at the highest level on future issues concerning human beings, society, culture, environment, and technology, supported by competent employees in administration, IT, and technology. LMU has an excellent research infrastructure and a large international network. It offers attractive opportunities for academic careers and supports its members through various measures and programs in personal development, the unfolding of their talents, and the shaping of their working environment at the university.</p>
<div class="g-clear"></div>
