---
title: "The Faculty of Business Administration becomes an official Institutional Member"
date: 2024-07-16
---


<p>The Faculty of <a href="../../members/institutional-members/faculty_of_business_management/index.html" target="_blank" title="Faculty of Business Administration - Munich School of Management">Business Administration</a> has been supporting the OSC financially since 2021. In 2024, they now become an official Institutional Member approved by their Faculty Committee with the following statement:</p>
<p>"The LMU Munich School of Management is committed to advancing the principles of open science and research transparency. By becoming an institutional member of the LMU's Open Science Center, we aim to foster a culture of openness, collaboration, and integrity in our research community. We believe that promoting open access to data, methodologies, and findings will enhance the quality and reproducibility of research in business studies, ultimately contributing to innovative and impactful solutions for global business challenges."</p>
<p>We are excited about their commitment and look forward to working even more closely together!</p>
<p> </p>
<div class="g-clear"></div>
