---
title: "Stellenausschreibung: Wissenschaftlicher Koordinator (m/w/d) für Open Science"
date: 2024-07-15
subtitle: "von 01/01/2025 bis 31/10/2027 - Bewerbungsschluss 15.07.2024!"
categories: ["Job Ads"]
---

<h2 class="g-h2 heading">Downloads</h2>
<ul class="g-ul bd">
<li class="g-pdf">
        <a href="jobadeng.pdf" target="_blank">Job ad Scientific Coordinator (English)</a>
        <span class="g-color-light g-fontsize-s">(557 KByte)</span>
</li>
        <li class="g-pdf">
        <a href="jobarger.pdf" target="_blank">Stellenausschreibung Wissenschaftlicher Koordinator (Deutsch)</a>
        <span class="g-color-light g-fontsize-s">(565 KByte)</span>
</li>
        </ul>

<p>Das LMU Open Science Center (OSC) sucht ab dem <strong>1. Januar 2025 bis zum 31. Dezember 2027</strong> eine Vollzeit- oder zwei Teilzeitstellen als:</p>
<p><strong>Wissenschaftlicher Koordinator (m/w/d) für Open Science (E13 TV-L)</strong></p>
<p>Das OSC ist eine interdisziplinäre, von Forschern geleitete Initiative der Ludwig-Maximilians-Universität München (LMU), die offene Forschungspraktiken an der LMU und darüber hinaus fördert. Wir suchen einen hoch motivierte und organisierte Person als Wissenschaftlichen Koordinator, um die Umsetzung innovativer Programme zu leiten, die durch das Volkswagen Foundation Pionierprojekt finanziert werden: <a href="https://portal.volkswagenstiftung.de/search/projectDetails.do?ref=9D211">“From local to systemic implementation: Embedding open research in institutional practices”.</a> Dies ist eine einzigartige Gelegenheit, um einen kulturellen Wandel hin zu einer transparenten und reproduzierbaren Forschung voranzutreiben, an einer der führenden Universitäten Deutschlands, am Fuße der Alpen. Eine Verlängerung des Vertrags wird angestrebt, sofern eine Finanzierung über interne Mittel oder Drittmittel möglich ist.</p>
<p><strong>Ihre Aufgaben:</strong></p>
<ul>
<li>Mitentwicklung, Koordination und Umsetzung eines umfassenden "Train-the-Trainer"-Programms für Open Science an der LMU, das Teilnehmer befähigt, Botschafter für offene Forschung in ihren Disziplinen zu werden.</li>
<li>Unterstützung beim Community-Management von FORRT (Framework for Open and Reproducible Training), um die gemeinsame Entwicklung des Train-the-Trainer-Programms zu koordinieren.</li>
<li>Zusammenarbeit mit der anderen wissenschaftlichen Koordinatorin bei der Entwicklung und Durchführung eines "Switch-to-Open"-Programms. Dieses Programm unterstützt Forschungsgruppen verschiedener Disziplinen dabei, von einem geschlossenen zu einem offenen Arbeitsablauf zu wechseln, z. B. durch die Entwicklung eines maßgeschneiderten schriftlichen Leitfadens (“standard lab practices”) für offene Forschungspraktiken.</li>
<li>Durchführung interdisziplinärer Workshops, Seminare und Networking-Veranstaltungen zu offenen Forschungspraktiken.</li>
<li>Evaluationsstudien zur Bewertung der Wirksamkeit und zur kontinuierlichen Verbesserung des Programms.</li>
</ul>

<p><strong>Voraussetzungen:</strong></p>
<p><strong></strong>Der ideale Kandidat/die ideale Kandidatin verfügt über folgende Qualifikationen:</p>
<ul>
<li>Master- oder Doktortitel in einem relevanten Fachbereich (z. B. Sozialwissenschaften, Naturwissenschaften, Medizin, Bibliothekswissenschaft, Digitale Geisteswissenschaften).</li>
<li>Vertrautheit mit den Prinzipien offener und reproduzierbarer Forschung.</li>
<li>Projektmanagementfähigkeiten, einschließlich Planung, Koordination und Bewertung.</li>
<li>Fähigkeit zur selbstständigen und kooperativen Arbeit in interdisziplinären Teams und Förderung einer Kultur der Inklusivität und Offenheit.</li>
<li>Ausgezeichnete Kommunikationsfähigkeiten mit der Kompetenz, vielfältige Interessengruppen zu engagieren und zu inspirieren.</li>
<li>Englischkenntnisse sind erforderlich. Bei gleichen Qualifikationen bevorzugen wir einen Kandidaten/eine Kandidatin, der/die Deutsch spricht (C1-Level).</li>
</ul>

<p>Auch falls sie noch nicht alle aufgeführten Qualifikationen erfüllen, werden Bewerber/innen mit einer starken Lernbereitschaft ermutigt, sich zu bewerben und ihr Potenzial zu demonstrieren.</p>
<p><strong>Was wir bieten</strong></p>
<p>Das LMU Open Science Center war das erste interdisziplinäre Zentrum für Open Science, das an einer Universität in Deutschland gegründet wurde. Der eingestellte Kandidat/die eingestellte Kandidatin wird die Möglichkeit haben,</p>
<ul>
<li>sich einem interdisziplinären Team und einer Community leidenschaftlicher Befürworter offener Forschung anzuschließen.</li>
<li>einen Einfluss auf die Transparenz der Forschung an einer führenden europäischen Universität und darüber hinaus zu haben.</li>
<li>zur Bildung eines lebendigen Netzwerks beizutragen, innerhalb der LMU, FORRT und darüber hinaus.</li>
<li>flexible Home-Office-Möglichkeiten zu nutzen.</li>
</ul>

<p>Schließen Sie sich uns an, um positive Veränderungen voranzutreiben und die Zukunft der akademischen Forschung mitzugestalten!</p>
<p><strong>Bewerbungsverfahren</strong></p>
<p>Interessierte Kandidaten/Kandidatinnen senden bitte ihren Lebenslauf und ein Anschreiben, in englischer oder deutscher Sprache, in dem sie ihre relevanten Erfahrungen und Motivation darlegen, als ein kombiniertes PDF an <a href="mailto:malika.ihle@lmu.de">malika.ihle@lmu.de</a>, mit dem Betreff: 'Application for Open Science Coordination'. Stichtag ist der <strong>15. Juli</strong>. Die Auswahlgespräche finden vom 25. bis 31. Juli in englischer Sprache statt (online oder persönlich).</p>
<p>Die LMU strebt eine Erhöhung des Anteils von Frauen in akademischen Positionen an und ermutigt daher nachdrücklich Wissenschaftlerinnen, sich zu bewerben. Bei gleichen Qualifikationen erhalten behinderte Bewerberinnen und Bewerber den Vorzug.</p>
<p>Für Rückfragen steht Prof. Dr. Felix Schönbrodt per E-Mail unter <a href="mailto:felix.schoenbrodt@psy.lmu.de">felix.schoenbrodt@psy.lmu.de</a> zur Verfügung.</p>
<p> </p>
<p>Im Rahmen Ihrer Bewerbung auf eine Stelle an der Ludwig-Maximilians-Universität München (LMU) übermitteln Sie personenbezogene Daten. Beachten Sie bitte hierzu unsere Datenschutzhinweise gemäß Art. 13 Datenschutz- Grundverordnung (DSGVO) zur Erhebung und Verarbeitung von personenbezogenen Daten und die Datenschutzerklärung der LMU für den Internetauftritt. Durch die Übermittlung Ihrer Bewerbung bestätigen Sie, dass Sie die Datenschutzhinweise und die Datenschutzerklärung zur Kenntnis genommen haben und mit der Datenverarbeitung im Rahmen des Auswahlverfahrens einverstanden sind.</p>
<p>Die Ludwig-Maximilians-Universität München zählt zu den besten und erfolgreichsten Universitäten Europas mit derzeit rund 15.000 Beschäftigten und ca. 52.000 Studierenden. Seit vielen Jahren ist sie als Exzellenzuniversität ausgezeichnet und erbringt Spitzenleistungen in Forschung und Lehre. An der LMU arbeiten Wissenschaftlerinnen und Wissenschaftler auf höchstem Niveau an den Zukunftsfragen um Mensch, Gesellschaft, Kultur, Umwelt und Technologie — unterstützt durch kompetente Beschäftigte in Verwaltung, IT und Technik. Die LMU verfügt über eine hervorragende Forschungsinfrastruktur und ein großes internationales Netzwerk. Sie bietet attraktive Entwicklungsmöglichkeiten für die wissenschaftliche Karriere. Und nicht zuletzt unterstützt sie ihre Mitglieder mit vielen Maßnahmen und Programmen dabei, sich persönlich weiterzuentwickeln, ihre Talente zu entfalten und ihr Arbeitsumfeld an der Universität mitzugestalten.</p>
<div class="g-clear"></div>
