---
title: "11 strategies for making reproducible research the norm at LMU Munich"
date: 2025-01-08
subtitle: "by the LMU Open Science Center"
---


<p>In an age where trust in science is critical, making research open and reproducible is not just ideal—it is essential. Some members of the LMU Open Science Center have contributed to the publication <a href="https://elifesciences.org/articles/89736">“Eleven strategies for making reproducible research and open science training the norm at research institutions”</a>, which provides a detailed roadmap for implementing transparent and reproducible research at institutions. At LMU Munich, many of these strategies have already been put into practice.</p>
<p>The strategies are divided into three dimensions: First, “adapting research assessment criteria and program requirements” [strategies 1–3]; second, “training” [strategies 4–8], and third, “building communities” [strategies 9–11].</p>
<p>These dimensions address critical aspects of fostering a culture of open and reproducible research. Below, we outline the 11 strategies and provide examples for their implementation at LMU Munich.</p>
<p><strong>Strategy 1: Adapt curriculum to require reproducibility and open science training</strong></p>
<p>To ensure that students develop a strong foundation of open science knowledge it is important to adapt official curricula at universities. An example of this is the core curriculum for empirical practice course for undergraduate Psychology students at LMU Munich (<a href="https://www.fak11.lmu.de/dep_psychologie/studium/lehrelounge/kerncurriculum_empra/index.html">https://www.fak11.lmu.de/dep_psychologie/studium/lehrelounge/kerncurriculum_empra/index.html</a>). These cover essential open science topics such as FAIR data sharing or preregistration. By learning about open science from an early stage, students develop important habits for their future careers which is fundamental for making open research practices the norm.</p>
<p><strong>Strategy 2: Require reproducible research and open science practices in undergraduate and graduate theses</strong></p>
<p>At the LMU Department of Psychology, PhD students need to decide on a list of open science practices with their supervisors before they start their research. A completed disclosure form highlighting the implemented practices is part of their final PhD thesis submission. Read more and find templates at: <a href="https://www.fak11.lmu.de/dep_psychologie/osc/dissertation_agreement/index.html">https://www.fak11.lmu.de/dep_psychologie/osc/dissertation_agreement/index.html</a></p>
<p>To incentivise change, it is important that institutions recognize and reward these practices:</p>
<p><strong>Strategy 3: Include reproducible and open science practices in research(er) assessment</strong></p>
<p>To acknowledge researchers following open science principles, the LMU Department of Psychology requires applicants for professor positions to provide statements on how they have implemented open science practices in their past work and plan to implement them in the future.</p>
<p>Such change in hiring procedures is supported by the LMU Open Science Center (OSC) for all the LMU Faculties who are institutional members of the OSC.</p>
<p>Fostering a culture of open science also requires providing researchers the tools and training they need to implement in their research.</p>
<p><strong>Strategy 4: Offer reproducible research and open science courses</strong></p>
<p>As a grassroots initiative whose main activity is to provide peer-to-peer training, the LMU Open Science Center offers various workshops, lectures, and a yearly week-long summer school to impart transparent and reproducible research skills. Check out the material of past events and register for upcoming events at <a href="https://www.osc.uni-muenchen.de/events/index.html">https://www.osc.uni-muenchen.de/events/index.html</a>.</p>
<p><strong>Strategy 5: Integrate reproducibility and open science skills into courses on other topics</strong></p>
<p>Even if courses are not specifically about open science, but e.g. about research methodology, instructors can integrate elements of open research training like reproducible workflow tools, research data management, or skills to critically evaluate publication standards into their course. This way, rigorous and transparent practices are embedded in official curricula without requiring more teaching hours. Many of the 100+ OSC members have adopted this strategy, for instance <a href="../../members/individual_members/fellows/mandl1/index.html" title="Mandl">Maximilian Mandl</a> in his course “Grundlagen der Reproduzierbarkeit und Replizierbarkeit in der Statistik” for statisticians.</p>
<p><strong>Strategy 6: Provide hands-on training</strong></p>
<p>Practical hands-on experience is essential for adopting reproducible research practices effectively. For this, members of the LMU Open Science Center have developed several self-paced tutorials on computing skills which can be found in our GitHub organization <a href="https://github.com/lmu-osc">https://github.com/lmu-osc</a>. Anyone is welcome to use them for self-learning or for teaching. These tutorials provide step-by-step guidance to implement new skills directly into a researcher's workflow.</p>
<p>Additionally the OSC collaborates with the Carpentries to teach researchers how to become instructors of essential coding, data analysis, and reproducible research skills. With our newly trained instructors, we offer many hands-on workshops by demonstrating ‘live’ how to programme, while students follow along.</p>
<p>Sometimes, however, our workshop or summer school’s attendees return to their lab and struggle to implement their newly learned skills because of a disconnect with the practices of the rest of their team.</p>
<p><em>Perhaps, providing training to the entire research group could have the most transformative impact:</em></p>
<p><strong>Strategy 7: Conduct educational interventions for research groups</strong></p>
<p>A synchronous and collective switch from closed to open research practices by all members of a research group could ease the adoption of open research practices. The LMU Open Science Center just started to provide close and tailored consultations to individual research groups, providing resources to the team members such as our self-paced tutorials on essential computing skills, but also discipline specific self-learning resources to bridge their knowledge and skills gap together. The consultant and the team members are then writing together a standard open research practice guide that can be used as an onboarding document for new group members. This programme is part of the project ‘From local to systemic implementation: Embedding open research in institutional practices’ funded by the Volkswagen Foundation for 2025-2027 (<a href="https://www.osc.uni-muenchen.de/news/vw_report/index.html">read more</a>).</p>
<p><em>To foster critical thinking, metascientific projects and study replications can be integrated into course projects.</em></p>
<p><strong>Strategy 8: Perform replication or meta-research studies as course projects</strong></p>
<p>A member of the LMU Open Science Center, <a href="../../members/individual_members/associated-members/seibold1/index.html" title="Seibold">Dr. Heidi Seibold</a>, developed a course which aimed to reproduce longitudinal data analyses from various research articles, highlighting the challenges of computational reproducibility when source code is unavailable (<a href="https://journals.plos.org/plosone/article?id=10.1371/journal.pone.0251194">https://journals.plos.org/plosone/article?id=10.1371/journal.pone.0251194</a>).</p>
<p>In addition to internal efforts, we are also inspired by the work of a previous guest speaker, <a href="https://mgto.org">Prof. Gilad Feldman</a>, who supports the use of the Registered Report format when supervising student replication projects. His work sets a high standard for integrating reproducible practices into coursework (the slides from his workshop can be found here: <a href="https://osf.io/6vhsw/">https://osf.io/6vhsw/</a>.</p>
<p><em>Besides imparting students and researchers with knowledge and skills for conducting open research, building communities around these practices further facilitates their adoption.</em></p>
<p><strong>Strategy 9: Organize journal clubs and other community-learning opportunities</strong></p>
<p>One effective way to foster collaboration and networking in academic communities is to organize gatherings like journal clubs, Hacky Hours, or discipline-specific meetups. By establishing a collaborative environment, researchers can exchange ideas, pieces of expertise, and practical tips, as well as explore limitations.</p>
<p>A great venue for that is the ReproducibiliTea Journal Club where researchers and students critically discuss papers and reflect on various open science practices. Read about other meetups the LMU Open Science Center supports at <a href="https://www.osc.uni-muenchen.de/meetups/index.html">https://www.osc.uni-muenchen.de/meetups/index.html</a></p>
<p><strong>Strategy 10: Creating resource hubs</strong></p>
<p>Resource hubs act as a central point for collecting and distributing resources at research institutions. The LMU Open Science Center is a network of 100+ members who contribute training resources, organize debates, symposia, and conferences, and who lobby, within their respective committees, in favor of open science. Learn how LMU members can join our community of advocates here: <a href="https://www.osc.uni-muenchen.de/join/index.html">https://www.osc.uni-muenchen.de/join/index.html</a></p>
<p><strong>Strategy 11: Connect individuals and initiatives involved in reproducible research and open science practices</strong></p>
<p>The LMU Open Science Center coordinates different initiatives both within and beyond the university: Internally, the center coordinates activities across its sub-initiatives e.g. the Open Science Initiative in Medicine (OSIM). Externally, it serves as e.g. the local node of the <a href="https://reproducibilitynetwork.de">German Reproducibility Network</a>, connecting LMU with national and international efforts.</p>
<p><em>By implementing these strategies, LMU Munich is helping to make reproducible research and open science standard practices in academia. Each step we take, from revising curricula to fostering collaboration, strengthens a culture of transparency and rigour at our institution and beyond.</em></p>
<div class="g-clear"></div>
