---
title: "Launching of LMU-FORRT Train-the-Trainer Program"
date: 2025-07-10
---


<p><strong>LMU Open Science Center launches Train-the-Trainer program to advance open research practices in partnership with the Framework for Open and Reproducible Research Training (FORRT)</strong></p>
<p>The <strong>Open Science Center (OSC)</strong> of the Ludwig-Maximilians-Universität München (LMU) is excited to introduce the <strong>Train-the-Trainer program</strong>, <a href="https://www.lmu.de/en/newsroom/news-overview/news/bringing-transparency-to-research-practice.html" target="_blank">funded by the VW Foundation</a>. This initiative aims to <strong>promote open and reproducible research across academic disciplines</strong>. It equips researchers not only with hands-on Open Science skills for themselves, but also with the tools and knowledge to <strong>train other students and researchers in open research practices</strong> within their own fields.</p>
<p><strong>The OSC staff on the Train-the-Trainer program are:</strong></p>
<p><strong>Sarah von Grebmer</strong> is the Train-the-Trainer Program Coordinator. She coordinates, develops and delivers the “Train-the-trainer” program to future Open Science trainers, and facilitates interdisciplinary workshops, seminars, and networking events to engage and support participants in adopting open research practices.</p>
<p><strong>Sara Lil Middleton</strong> is the Training Development Coordinator and Community Engagement Manager. She develops training content and manages and integrates contributions from the FORRT community. She will also co-develop auxiliary content to facilitate the longer-term engagement of Open Science practices beyond the completion of training courses.</p>
<p><strong>Reema Gupta</strong> is the OSC's FAIR data sharing expert. She specializes in data management, research data standards, and reproducible workflows. She creates training materials and provides consultations to researchers on these topics.</p>
<p>A key strength of the program lies in its close partnership with the<strong> Framework for Open and Reproducible Research Training</strong> (<a href="http://forrt.org">FORRT</a>) community. This partnership reflects a shared commitment to systemic reform in research culture through education, grassroots collaboration, and equitable infrastructure. The FORRT project is an <strong>international</strong> and <strong>interdisciplinary</strong> <strong>community project</strong> that promotes and curates<strong> Open Science training resources and meta-research</strong>, and is committed to democratizing access to both learning and teaching materials in Open Science, ensuring equitable participation across career stages, disciplines, and geographies. For this partnership with the LMU OSC, FORRT contributes with expertise in Open Science pedagogy, inclusive education, participatory infrastructure-building, and metascience. Moreover, FORRT ensures that the Train-the-Trainer program also embeds diversity, equity, inclusion, and accessibility (DEIA) throughout. Its community developed resources, including training modules, lesson plans, and glossaries are integrated throughout to help ensure alignment with global Open Science values.</p>
<p>Over a three-year period, the program aims to train around 50 instructors, who will then go on to train students and researchers within their respective disciplines. The <strong>curriculum</strong> includes topics such as <strong>methodological foundations of Open Science, computational reproducibility, tools for collaborative working, data management and data sharing</strong>. In addition, the curriculum also includes crucial modules on <strong>pedagogical skills in teaching about Open Science, such as basic didactic skills, activation tools for student-trainer interactions, leadership skills as well as modules on broader issues connected to teaching Open Science such as diversity, accessibility and cultural awareness.</strong> It will be delivered through interactive flipped-classroom formats and as self-paced hands-on online materials. Participants will receive certification upon completion, ensuring academic recognition of their new skills. In this, the program aims to build sustainable capacity within departments and to create a multiplier effect, fostering systemic shifts toward transparency and openness.</p>
<p><br><em>“We want to create a freely accessible program covering not only the know-how of open research Practices, but also to provide program participants with the pedagogical tools to confidently pass on their knowledge about Open Science to different audiences.”</em><br>— Dr. Sarah von Grebmer zu Wolfsthurn, LMU OSC Train-the-Trainer Program Coordinator</p>
<p><br><em>"At FORRT, we believe that equipping educators with both the tools and the values of Open Science is key to changing how research is taught and practiced. This collaboration with LMU is about more than building skills— it's about cultivating a culture of transparency, inclusion, and better research and teaching practices across disciplines and borders."</em><br>— Dr. Flavio Azevedo, Director of FORRT</p>
<p><br>For any questions about the Train-the-Trainer program, please get in touch with the Train-the-Trainer program coordinator, Dr. Sarah von Grebmer zu Wolfsthurn (<a class="g-link-mail" href="mailto:s.grebmer@lmu.de" title="Send email to: s.grebmer@lmu.de">s.grebmer@lmu.de</a>).</p>
<div class="g-clear"></div>
