---
title: SHARP Becomes an Official Institutional Member
date: 2026-05-05
categories: ["New Members"]
description: Collaborative Research Centre, TRR419 SHARP becomes an official funding institutional member of the OSC!

template: templates/news-template.html
filters:
  - templates/process-news-yaml.lua
---

Research Centre TRR419 [Simulation-Based Learning in Higher Education (SHARP)](https://www.en.mcls.uni-muenchen.de/research/sharp-initiative/index.html) became the newest [funding Institutional Member](/partners/funding-institutional-members.qmd) to support the OSC! Their dedication to Open Science and Research is detailed in their statement below:

"As a DFG-funded Collaborative Research Centre, TRR419 SHARP is committed to advancing rigorous, transparent, and reproducible research in the learning sciences. Our work brings together interdisciplinary expertise from LMU Munich, TUM, the University of Augsburg, and the Leibniz Supercomputing Centre to investigate simulation-based learning, process diagnostics, and AI-supported personalized interventions in higher education. As an institutional member of the LMU Open Science Center, we support the development of open research practices, sustainable research data management, and reproducible workflows across collaborative projects. Our involvement reflects our commitment to methodological rigor, shared infrastructures, and the transparent dissemination of scientific knowledge in interdisciplinary and data-intensive research."

**Effective collaboration has already begun**:

-   OSC coordinator [Malika Ihle](/people/people/malika-ihle.qmd) offered training to SHARP Center’s PhD students in April 2026 to introduce and discuss the advantages of various open research practices! Check out the slides to learn about what was covered during this training session: <https://osf.io/p9sev/files/b2rey>

-   Principal Investigator [Prof. Dr. Anne Frenzel](/people/people/anne-frenzel.qmd)'s research team is partaking in the [Switch to Open Program (SwOP)](/training/research-cycle-handbook.qmd)! This involves consultations on their research practices and a co-creation of a tailored research practices lab handbook.

We are thrilled to welcome SHARP as an Institutional Member and look forward to more collaborations in the future!
