---
title: The Department of Educational Sciences joins the OSC 
date: 2026-09-23
categories: ["New Members"]
description: The OSC welcomes the Department of Educational Sciences as our new funding institutional member!

template: templates/news-template.html
filters:
  - templates/process-news-yaml.lua
---

We are delighted to welcome the [Department of Educational Sciences](https://www.lmu.de/edu/en/) as our newest [Funding Institutional Member](/partners/funding-institutional-members.qmd).

The department extends their commitment to open science through their partnership with OSC, as outlined in their [mission statement](/partners/funding-institutional-members.qmd): "As an institutional member of the LMU Open Science Center, we support the adoption of open, transparent, and reproducible research practices in educational research and beyond. Our partnership reflects our shared commitment to methodological rigor, responsible research, and fostering a culture of openness that strengthens both scientific progress and educational practice."

We look forward to advancing open science together!