---
config:
  theme: default
  look: classic
---

flowchart TD
  A["Manuscript Draft<br>(Preprint v0.0)"] -->|community feedback| B["Submitted Manuscript<br>(Preprint v1.0)"]
  B -->|journal peer review| C["Revised Manuscript<br>(Preprint v2.0)"]
  C -->|journal acceptance| D["Postprint<br>(Preprint v3.0)"]
    D -->|journal copy-editing and formatting| E["Published Article"]