---
title: "Educator toolkit"
---

Are you a university educator or study program coordinator that is curious or passionate about Open Research? Are you keen to add more Open Research content into your courses or class rooms but not sure how? 

If that sounds like you, then our educator toolkit could be for you!

# What is the educator toolkit?

Our educator toolkit follows a 'train-the-trainer' model, where we provide support/training materials for educators to build on their existing Open Research knowledge and pedagogy skills to deliver high quality and engaging Open Research content for their learners.

The educator toolkit aims to:

- **Promote** open and reproducible research across academic disciplines
- **Provide** educators with in-depth pedagogical skills to confidently **train others in Open Research practices**  e.g., students, lab members, or other researchers from the same or even a different field. 

# What training is available?

We understand the time pressures of being an educator, and so have designed our training to be modular to help fit around your busy schedule. We offer:

- Ready-to-use materials for teaching Open Research practices on topics including **methodological foundations of Open Science, computational reproducibility, tools for collaborative working, data management and data sharing**

- Training materials and practical tips on engaging and effective teaching strategies covering topics on **critical pedagogical skills, didactics, activation methods for learners, leadership in open science and accessibility**

- Opportunity for hands on training in Open Research and pedagogy at our annual Open Science Summer School (LINK to OSSS25) (2026 date TBC)

Training materials are grounded in pedagogical theory, and depending on the topic, materials come in a variety of formats (Quarto slides, HTML, PDF, MS PowerPoint and Google Documents).

# I am interested, how do I get started?
Depending on your interest, level of expertise and your own goal, there are **four** entry points to using the educator toolkit.

## The Open Research modules: For those who want to learn

Are you new to Open Research and currently have no idea what we are talking about? Have you heard about Open Research before and would like to develop your skills? Or are you already a pro at Open Research but need a refresher or are missing a specific Open Research practice? Then you have come to the right place!

- If you are (practically) new to Open Research, follow the curriculum here: LINK

- If you are have previous knowledge and skills in Open Research, follow the curriculum here: LINK

## The pedagogy modules: For those who want to teach

Did you just acquire knowledge and skills in Open Research and want to spread your wisdom? Have you been thinking about giving a workshop to your lab group about an Open Research topic, but are encountering resistance or little motivation? Or are you a university educator, who would like to bring the topic of Open Research closer to your learners or students? Then this content is for you!

- If you are planning on teaching novices or students, follow the curriculum here: LINK

- If you are planning on teaching researchers or research support staff, follow the curriculum here: LINK

Still unsure where to get started? Feel free to get in touch with Dr Sarah von Grebmer (s.grebmer@lmu.de). 

The educator toolkit has been developed in partnership with the Framework for Open and Reproducible Research Training [FORRT](http://forrt.org) community together with funding by the [VolksWagen Foundation](https://www.volkswagenstiftung.de/de). Our training materials are licenced under a [CC-BY-SA 4.0](https://creativecommons.org/licenses/by-sa/4.0/deed.en) Attribution-ShareAlike 4.0 International.


################################################################

# Welcome!

Are you a university educator or study program coordinator that is curious or passionate about Open Research? Are you keen to add more Open Research content into your courses or class rooms but not sure how? 

If that sounds like you, then our **educator toolkit** is for you!

## What is the educator toolkit?

Our educator toolkit follows a 'train-the-trainer' model, where we provide support/training materials for educators to build on their existing Open Research knowledge and pedagogy skills to deliver high quality and engaging Open Research content for their learners.

The educator toolkit aims to:

- **Promote** open and reproducible research across academic disciplines
- **Equip** educators with high quality, **ready-to-use materials** to use across different learning contexts, e.g., classrooms or lab meetings
- **Provide** educators with in-depth pedagogical skills to confidently **train others in Open Research practices**  e.g., students, lab members, or other researchers from the same or even a different field. 

## What training is available?

We understand the time pressures of being an educator, and so have designed our training to be modular to help fit around your busy schedule. We offer:

- Ready-to-use materials for teaching Open Research practices on topics including **methodological foundations of Open Science, computational reproducibility, tools for collaborative working, data management and data sharing**

- Training materials and practical tips on engaging and effective teaching strategies covering topics on **critical pedagogical skills, didactics, activation methods for learners, leadership in open science and accessibility**

- Opportunity for hands on training in Open Research and pedagogy at our annual Open Science Summer School (LINK to OSSS25) (2026 date TBC)

Training materials are grounded in pedagogical theory, and depending on the topic, materials come in a variety of formats (Quarto slides, HTML, PDF, MS PowerPoint and Google Documents).


::: {.callout-important}
Are you **new to Open Research** and currently have no idea what we are talking about? Then we strongly recommend **developing your own Open Research knowledge and skills** following either this course HERE to gain both theoretical and practical experience with Open Research. Have you heard about Open Research before and would like to **develop your skills further**? Or are you already a pro at Open Research but need a **refresher** or are missing a specific Open Research practice? Then browse through our **catalogue** to tailor your skill set.

- If you are (practically) new to Open Research, follow the curriculum here: LINK

- If you are have previous knowledge and skills in Open Research, follow the curriculum here: LINK

:::

## I am interested, how do I get started?

Did you just acquire knowledge and skills in Open Research and want to spread your wisdom? Are you missing some crucial pedagogical skills to successfully convey Open Research content to students or fellow researchers? You have come to the right place! There are **two** entry points to using the educator toolkit depending on your **intended audience**. Pick one of the curricula on pedagogical skills below depending on your audience: 

- Are you a university educator, who would like to bring the topic of Open Research closer to your **learners or students** but have no prior experience with teaching? Then follow the curriculum here: LINK

- Have you been thinking about giving a workshop on a specific Open Research topic to **fellow researchers** or **research support staff** and want to know the best way to get your content across from a pedagogical perspective? Then follow the curriculum here: LINK


::: {.callout-note}
## Still unsure where to get started?
Feel free to get in touch with Sarah von Grebmer (s.grebmer@lmu.de).
:::

The educator toolkit has been developed by the [LMU Open Science Center](https://lmu-osc.github.io/) in partnership with the Framework for Open and Reproducible Research Training [FORRT](http://forrt.org) community together with funding by the [VolksWagen Foundation](https://www.volkswagenstiftung.de/de). Our training materials are licenced under a [CC-BY-SA 4.0](https://creativecommons.org/licenses/by-sa/4.0/deed.en) Attribution-ShareAlike 4.0 International.
