---
title: 'LMU Open Science Summer School 2025' 
date: "15 Sep, 2025"
end_date: "19 Sep, 2025"
categories: ["Summer school"]
description: "The LMU Open Science Center (OSC) is excited to announce the call for applications for its 5th hybrid summer school (OSSS25): deadline July 14! This year's iteration has two tracks to provide participants with two sets of skills. You are invited to apply for one or both tracks. For either track, you can choose to participate either online or in-person."
time: "14:00 CET"
location: "Philologicum Library"
host: "LMU Open Science Center"
contact: 
    name: "OSC team"
    email: "osc@lmu.de"
event-lang: "en"
form: "Hybrid"
format: 
    html:
        table-of-contents: false
        css: styles1.css
page-layout: full
---
<!-- Load Font Awesome (goes right after YAML) -->
<link rel = "stylesheet"  href = "https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.2/font/bootstrap-icons.css">

```{=html}

<div class = "event-detail">
    <div class="event-location event-item">
        <a href="https://www.google.com/maps/place/Ludwigstraße+25,+80539+München,+Germany" target="_blank" style="text-decoration: none; color: inherit;">
        <div class="location-container">
          <i class="bi bi-geo-alt-fill"></i>
          <div class="location-text">
            Philologicum Library, Ludwigstraße 25, 80539 Munich 
          </div>
        </div>
        </a>
    </div>
    <div class="event-meta">
        <div class="meta-item">
            <div class="meta-label">📅 Date & Time</div>
            <div class="meta-value">15 -19 September, 2025<br>14:00 - 17:00 CET</div>
        </div>
        <div class="meta-item">
            <div class="meta-label">🌐 Language</div>
            <div class="meta-value">English<br>(German Q&A available)</div>
        </div>
        <div class="meta-item">
            <div class="meta-label">💻 Format</div>
            <div class="meta-value">Hybrid Event<br>In-person & Online</div>
        </div>
    </div>
    <div class = "register-button">
        <a href="https://www.pretix.osc.lmu.de/lmu-osc/OSSS25/" target = "_blank">Register</a>
    </div>

</div>

```


#### **Overview**
The LMU Open Science Center (OSC) is excited to announce the call for applications for its 5th hybrid summer school (OSSS25): **deadline July 14!**

This year's iteration has two tracks to provide participants with two sets of skills. You are invited to apply for one or both tracks. For either track, you can choose to participate either online or in-person.

**Track 1: Open Science knowledge and skills**

In this track, early career researchers who are Open Science novices learn to make their research more transparent, reproducible and credible in the eyes of their peers, the public, and funding agencies. This track consists of public lectures accessible to anyone as well as hands-on practical workshops for selected applicants and extends from Monday 15.09.2025 9:00 to Friday 19.09.2025 14:30.

Participants of this track learn how to:

- Specify research design and set up statistical plans in advance of collecting data to prevent biases in analyses, with the help of preregistration and data simulation. 
- Create computationally reproducible workflows to be more efficient and spot mistakes in data wrangling or analyses, through programming with version controlled scripts. 
- Prepare and share data and code in connection with manuscripts by applying the Findable, Accessible, Interoperable, Reusable principles, and using adequate repositories and licenses to accumulate credit and citations.

**Track 2: Open Science instructor training**

In this track, early career researchers or research support staff interested in becoming Open Science instructors develop essential pedagogical skills to promote Open Science through teaching - no prior experience in teaching required. This track extends from Friday 19.09.2025 14:30 to 17:30.

Participants of this track learn how to:

- Design and deliver Open Science workshops, and apply basic didactic techniques to diverse audiences.
- Apply activation methods in the classroom to foster motivation and attention.
- Develop skills to advocate for Open Science, to lead research groups and discussions around Open Science, and to analyse the potential challenges and issues around the implementation of Open Science practices.

After joining this track, you will have the opportunity to put your new skills into practice and co-deliver a workshop at LMU to become a certified Open Science instructor.

#### **Keynote presenters**
<div class="instructor-links">
* [Laura Meier](https://www.osc.uni-muenchen.de/members/individual_members/fellows/meier/index.html){target="_blank"}
* [Maximilian Frank](https://www.osc.uni-muenchen.de/members/individual_members/fellows/frank/index.html){target="_blank"}
* [Florian Kohrt](https://www.osc.uni-muenchen.de/members/individual_members/fellows/kohrt/index.html){target="_blank"}
</div>


#### **Questions?** 
We are looking forward to your participation! For any questions, please contact us at <span class="instructor-links">[osc@lmu.de](mailto:osc@lmu.de)</span>
