on:
  workflow_dispatch:
  push:
    branches: main

name: Quarto Publish

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2

      - name: Render and Publish
        uses: quarto-dev/quarto-actions/publish@v2
        with:
          target: gh-pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
         
          
      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
          
      - name: Add LRZ GitLab remote
        run: |
          git remote add lrz_gitlab_remote git@gitlab.lrz.de:lmu-open-science-center/lmu-osc-website.git
          git remote -v
          
      - name: Fetch and push all branches to remote
        run: |
          git fetch --all
          
      - name: Push all branches to new remote
        run: |
          # Loop through all local branches and push them to lrz_gitlab_remote
          for branch in $(git branch -r | grep -v '\->' | sed 's/  origin\///'); do
            git push lrz_gitlab_remote origin/$branch:$branch
          done
        
      