name: Render and Publish Site

on:
  workflow_dispatch:
  schedule:
    - cron: "0 23 * * 0"
  push:
    branches: [main]

permissions:
  contents: write

env:
  RENV_CONFIG_AUTO_SNAPSHOT: "false"
  RENV_CONFIG_SNAPSHOT_TYPE: "explicit"

jobs:
  build-github:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends \
            libcurl4-openssl-dev \
            libssl-dev \
            libxml2-dev

      - name: Install R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: renv

      - name: Install R Dependencies
        uses: r-lib/actions/setup-renv@v2
        with:
          cache-version: 1

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2

      - name: Restore Quarto freeze cache (github)
        uses: actions/cache@v3
        with:
          path: _freeze
          key: ${{ runner.os }}-quarto-freeze-github-${{ hashFiles('**/*.qmd') }}
          restore-keys: |
            ${{ runner.os }}-quarto-freeze-github-

      - name: Render (GitHub profile)
        uses: quarto-dev/quarto-actions/publish@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # this secret is always available for github actions
          QUARTO_PROFILE: github
        with:
          target: gh-pages

  build-production:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends \
            libcurl4-openssl-dev \
            libssl-dev \
            libxml2-dev

      - name: Install R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: renv

      - name: Install R Dependencies
        uses: r-lib/actions/setup-renv@v2
        with:
          cache-version: 1

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2

      - name: Restore Quarto freeze cache (production)
        uses: actions/cache@v3
        with:
          path: _freeze
          key: ${{ runner.os }}-quarto-freeze-production-${{ hashFiles('**/*.qmd') }}
          restore-keys: |
            ${{ runner.os }}-quarto-freeze-production-

      - name: Render Quarto Project (production profile)
        uses: quarto-dev/quarto-actions/render@v2
        env:
          QUARTO_PROFILE: preview
        with:
          to: html

      - name: Deploy to prod-pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          publish_dir: ./_site
          publish_branch: prod-pages
          github_token: ${{ secrets.GITHUB_TOKEN }}
         