on:
  workflow_dispatch:
  push:
    branches: main

name: Quarto Publish

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2

      - name: Render and Publish
        uses: quarto-dev/quarto-actions/publish@v2
        with:
          target: gh-pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Push to Remote
        env:
          REMOTE_USERNAME: ${{ secrets.RemoteUsername }}
          REMOTE_HOSTNAME: ${{ secrets.RemoteHostname }}
          REMOTE_PASSWORD: ${{ secrets.RemotePassword }}
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        run: |
          pwd
          git status
          git branch
          git checkout gh-pages
          git branch
          ls -a
          mkdir -p ~/.ssh
          echo '$SSH_PRIVATE_KEY' > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          sshpass -p '$REMOTE_PASSWORD' scp -r ./* '$REMOTE_USERNAME'@'$REMOTE_HOSTNAME':~/website

    